substitutions:
  name: camtest
  friendly_name: CAMtest

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "K6XZUUKsryYCX6drLXgURcsof/GwdI9AjnZdb/JYJIc="

packages:
  device_base_camera: !include common/device_base_camera.yaml
  esp32_camera: !include common/esp32_camera.yaml
  debug: !include common/debug.yaml

ota:
  password: "e4e348db5510f66889ccbdd58c278e40"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
esp32_camera:
  resolution: 1024x768