# CHANGEME: Set these variable to your liking
title: AquaPi powered by ESPHome
icon: assests/AquaPi Logo.svg
description: Powered by HomeAssistant & ESPHome
show_downloads: true
google_analytics: G-BPGR2QSCVL
theme: jekyll-theme-minimal
