# CHANGEME: Set these variable to your liking
title: AquaPi powered by ESPHome
logo: assests/logo88x88.png
description: Powered by HomeAssistant & ESPHome
show_downloads: false
google_analytics: G-BPGR2QSCVL
remote_theme: mmistakes/minimal-mistakes
author:
  avatar: assests/logo88x88.png
