title: ![logo](https://github.com/TheRealFalseReality/aquapi/blob/5e4a82a5755e06d9029109c4bd55601596198b7c/assests/image/AquaPi%20Logo.png)AquaPi for ESPHome
logo: assests/AquaPiLogo_small.png
description: Powered by HomeAssistant & ESPHome
show_downloads: false
google_analytics: G-BPGR2QSCVL
# theme: jekyll-theme-minima
remote_theme: jekyll/minima
minima:
  skin: dark
author:
  name: TheRealFalseReality
  email: contact@capitalcityaquatics.com
header_pages:
  - setup.md
  - blueprints.md
  # - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
social_links:
  - { platform: facebook,       user_url: "https://www.facebook.com/OfficialCapitalCityAquatics/" }
  - { platform: github,         user_url: "https://github.com/TheRealFalseReality" }
