# These substitutions allow the end user to override certain values
substitutions:
  name: "aquapi"
  friendly_name: "AquaPi"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: TheRealFalseReality.aquapi
    version: "1.01"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_esphome.yaml@main

wifi:
  ap:
    password: "password"

captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  
improv_serial:

# i2c Pins
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    name: "Internal LED"
    pin: GPIO2

# 18B20 sensor Pin
dallas:
  - pin: 16
    
sensor:
  # Internal Magnetic Sensor
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 60s

  # Internal Temp.
  - platform: internal_temperature
    name: "Internal Temperature"

  # Wifi Signal 
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Wifi %
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  # Uptime sensor
  - platform: uptime
    name: Uptime Sensor    

  # EZO Circuits (yellow - SCL/RX, blue - SDA/TX)
  # EZO Circuit - pH
  - platform: ezo
    icon: mdi:ph
    name: "pH"
    id: ph_ezo
    address: 99
    unit_of_measurement: ""
    accuracy_decimals: 2
    update_interval: 60s
    state_class: "measurement"

  # EZO Circuit - EC
  # Salinity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Salinity"
    id: ec_ezo
    address: 100
    unit_of_measurement: "ppt"
    accuracy_decimals: 2
    update_interval: 60s
    state_class: "measurement"

  # Specific Gravity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Specific Gravity"
    id: ec_ezo_sg
    address: 100
    unit_of_measurement: ""
    accuracy_decimals: 3
    update_interval: 60s
    state_class: "measurement"

  # # DHT
  # - platform: absolute_humidity
  #   name: Absolute Humidity
  #   temperature: air_temperature
  #   humidity: relative_humidity

  # # - platform: dht
  #   pin: 5
  #   temperature:
  #     name: "Temperature"
  #     id: air_temperature
  #   humidity:
  #     name: "Humidity"
  #     id: relative_humidity
  #   update_interval: 60s

  # Temperature Probes
  - platform: dallas
    # address: 0xe58000003203d628
    index: 0
    name: "Temperature"

  - platform: dallas
    # address: 0xe58000003203d628
    index: 1
    name: "Temperature 2"

binary_sensor:
  # Optical Sensor - LOW (yellow)
  - platform: gpio
    id: os_low
    pin: 
      number: 32
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Optical Sensor: Low"
    filters:
      - delayed_on: 30ms

  # Optical Sensor - HIGH (blue)
  - platform: gpio
    id: os_high
    pin: 
      number: 33
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Optical Sensor: High"
    filters:
      - delayed_on: 30ms

text_sensor:
  # Water Level
  - platform: template
    name: "Water Level"
    id: water_level
    lambda: |-
      if(id(os_high).state == true && id(os_low).state == true) {
        // Water Level is High
        return {"High"};
      }
      if(id(os_high).state == false && id(os_low).state == false) {
        // Water Level is Low
        return {"Low"};
      }
      if(id(os_high).state == false && id(os_low).state == true) {
        // Water Level is Normal
        return {"Normal"};
      } else {
        return {"Uknown or Error"};
      }

button:
  # Soft Restart
  - platform: restart
    name: "Restart"
  # # Soft Shutdown
  # - platform: shutdown
  #   name: "Shutdown"
  # # Safe Mode
  # - platform: safe_mode
  #   name: "Safe Mode"

  # Output Parameters
  # Output Salinity
  - platform: template
    name: "EC - Output - Salinity"
    id: ec_sal
    on_press:
      then:
        - lambda: |-
            id(ec_ezo).send_custom("O,EC,0");
            id(ec_ezo).send_custom("O,TDS,0");
            id(ec_ezo).send_custom("O,S,1");
            id(ec_ezo).send_custom("O,SG,0");
            
  # Output Specific Gravity
  - platform: template
    name: "EC - Output - Specific Gravity"
    id: ec_sg
    on_press:
      then:
        - lambda: |-
            id(ec_ezo).send_custom("O,EC,0");
            id(ec_ezo).send_custom("O,TDS,0");
            id(ec_ezo).send_custom("O,S,0");
            id(ec_ezo).send_custom("O,SG,0");
