substitutions:
  # names
  name: "aquapicamera"
  friendly_name: "AquaPiCamera"
  # App Version - Updated: 6/2024
  app_version: "2024.6.2-cam"

packages:
  common: !include common/device_base_common.yaml
  device_base_camera: !include common/device_base_camera.yaml
  aquapi: !include common/aquapi.yaml
  ota_https: !include common/ota_https_camera.yaml
  # debug: !include common/debug.yaml