substitutions:
  # names
  name: "aquapicamera"
  friendly_name: "AquaPiCamera"
  # App Version - Updated: 5/2024
  app_version: "1.0-c"

packages:
  device_base_camera: !include common/device_base_camera.yaml
  aquapi: !include common/aquapi.yaml
  # debug: !include common/debug.yaml
