substitutions:
  # names
  name: "aquapicamera"
  friendly_name: "AquaPiCamera"
  # App Version - Updated: 6/2024
  app_version: "2024.6.1"

packages:
  device_base_camera: !include common/device_base.yaml
  aquapi: !include common/aquapi.yaml
  ota_https: !include common/ota_https.yaml
  # debug: !include common/debug.yaml

light:
  - id: !extend status_led
    pin: 33