blueprint:
  name: Aquarium - ATO Automation
  description: Create an ATO (Automated-Top-Off) Automation. Turn on Water Pump when
    binary sensor is off, and stop when binary sensor is on. [More Info](https://community.home-assistant.io/t/aquarium-create-ato-automation-control-switches-based-off-a-sensor/600941)
    (v1.61) [Automation]
  domain: automation
  source_url: https://gist.github.com/TheRealFalseReality/651bc40bf0e539c767e5bac408962f82
  input:
    condition:
      name: Add Condition(s)
      description: Add conditions if needed
      default: []
      selector:
        condition: {}
    sensor:
      name: Binary Sensor
      description: Binary sensor used to detect water level.
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    switch:
      name: Water Pump
      description: Switch to turn on Water Pump to refill to normal level.
      selector:
        entity:
          filter:
          - domain:
            - switch
          multiple: false
    delay_on:
      name: On Delay
      description: Water Pump on delay.
      default: 0
      selector:
        duration: {}
    normal_time:
      name: Normal Off Delay
      description: Time delay when water level is Normal to turn off pump, helps prevent
        frequent refills.
      default: 0
      selector:
        duration: {}
    pump_max_time:
      name: Water Pump Max On Time
      description: Turn off water pump if exceeds a certain time to prevent over-flow.
      default:
        minutes: 5
      selector:
        duration: {}
    additional_actions:
      name: Additional Actions
      description: Add additional actions to the script. Will execute before everything
        else, each time the automation is triggered.
      default: []
      selector:
        action: {}
variables:
  condition: !input condition
  sensor: !input sensor
  switch: !input switch
  delay_on: !input delay_on
  normal_time: !input normal_time
  pump_max_time: !input pump_max_time
  additional_actions: !input additional_actions
alias: Aquarium ATO Binary
description: Control ATO pump with binary sensor.
trigger:
- platform: state
  entity_id: !input sensor
  for: !input delay_on
  to: 'off'
  alias: When Water Level is Low
- platform: state
  entity_id: !input sensor
  for: !input normal_time
  to: 'on'
  alias: When Water Level is Normal
- platform: state
  entity_id: !input switch
  to: 'on'
  for: !input pump_max_time
  alias: When ATO device is On for a set Time
- platform: state
  entity_id: !input switch
  to: 'on'
  for: '{{ pump_max_time * 1.5 }}'
- platform: state
  entity_id: !input switch
  to: 'on'
  for: '{{ pump_max_time * 2 }}'
- platform: state
  entity_id: !input switch
  to: 'on'
  for: '{{ pump_max_time * 2.5 }}'
- platform: state
  entity_id: !input switch
  to: 'on'
  for: '{{ pump_max_time * 3 }}'
action:
- if:
  - condition: !input condition
  then:
  - choose: []
    default: !input additional_actions
  - if:
    - condition: state
      entity_id: !input sensor
      state: 'off'
    then:
    - service: switch.turn_on
      entity_id: !input switch
    else:
    - service: switch.turn_off
      entity_id: !input switch
mode: single
