blueprint:
  name: Aquarium - Dosing Time Daily
  description: Turn on a switch to activate doser equipment for a certain amount of
    time each day. [More Info](https://community.home-assistant.io/t/aquarium-turn-on-a-switch-to-activate-doser-equipment-for-a-certain-amount-of-volume-or-time/600546)
    (v1.1.2) [Automation]
  domain: automation
  source_url: https://github.com/TheRealFalseReality/aquapi/blob/main/blueprints/automation/TheRealFalseReality/aquarium_dosing_daily.yaml
  input:
    condition:
      name: Add Condition(s)
      description: Add conditions if needed
      default: []
      selector:
        condition: {}
    doseName:
      name: Dose Name
      description: Name of what you are dosing (ex. Marine Trace).
      selector:
        text:
          multiline: false
          multiple: false
    doseSwitch:
      name: Doser Switch
      description: Switch that activates the Doser Equipment.
      selector:
        entity:
          domain:
          - switch
          multiple: true
    doser_time:
      description: Dosing Time.
      name: Dose Time
      default:
        minutes: 10
      selector:
        duration: {}
    time_start:
      name: Time to Start
      description: Time to start the Dose every day.
      default: '10:00:00'
      selector:
        time: {}
    doseTime_max:
      name: Dose Max Time
      description: 'Max time for the doser to be on, will automatically turn off Doser
        Switch after the set time has passed. Prevents Doser from overdosing. (Default:
        1hr)'
      default:
        hours: 1
      selector:
        duration: {}
    doseTime_max_1:
      name: Dose Max Time Fallback
      description: 'Max time for the doser to be on, will automatically turn off Doser
        Switch after the set time has passed. Prevents Doser from overdosing in case
        the first trigger fails. (Default: 6hrs)'
      default:
        hours: 6
      selector:
        duration: {}
    doseTime_max_2:
      name: Dose Max Time Failsafe
      description: 'Max time for the doser to be on, will automatically turn off Doser
        Switch after the set time has passed. Prevents Doser from overdosing in case
        the first and second trigger fails. (Default: 12hrs)'
      default:
        hours: 12
      selector:
        duration: {}
    notify:
      name: Persistent Notification (Recommended)
      description: Notify Home Assistant when script is executed.
      default: true
      selector:
        boolean: {}
    additional_actions:
      name: Additional Actions
      description: "Add additional actions to the script. Will execute before everything
        else.\n- Example: To send to Mobile Device using the official Home Assistant
        App:\n\n  Notifications -> Send a notification via mobile.YOUR_DEVICE_NAME\n
        \ ```\n  service: notify.YOUR_DEVICE_NAME\n  metadata: {}\n  data:\n    message:
        \"{{ notify_message }}\"\n    title: \"{{ notify_title }}\"\n  ```\n\n  Copy
        {{ notify_message }} into `message`. This will switch to \"yaml\" mode. Above
        is a completed example.\n"
      default: []
      selector:
        action: {}
trigger:
- platform: time
  at: !input time_start
- platform: state
  entity_id: !input doseSwitch
  to: 'on'
  for: !input doseTime_max
  id: max_time
- platform: state
  entity_id: !input doseSwitch
  to: 'on'
  for: !input doseTime_max_1
  id: max_time
- platform: state
  entity_id: !input doseSwitch
  to: 'on'
  for: !input doseTime_max_2
  id: max_time
variables:
  condition: !input condition
  doseSwitch: !input doseSwitch
  doseName: !input doseName
  doser_time: !input doser_time
  doseTime_max: !input doseTime_max
  doseTime_max_1: !input doseTime_max_1
  ddoseTime_max_2: !input doseTime_max_2
  time_start: !input time_start
  notify_title: '{{ doseName }}'
  notify_message: 'Dosing {{ doseName }}. Duration: {{ doser_time }}.'
  notify_title_fail: '{{ doseName }} Failed'
  notify_message_fail: "Failed to dose {{ doseName }} due to conditions not passing.\n
    Conditions: {{ condition }}"
  additional_actions: !input additional_actions
  notify: !input notify
  notify_message_fail_max: "Dose Time Exceeded for {{ doseName }}. Switch should have been switched Off to prevent overdosing."
  notify_title_fail_max: "Dose Time Exceeded"
action:
- if:
  - condition: !input condition
  then:
  - choose:
    - conditions:
      - condition: trigger
        id: max_time
      sequence:
      - service: switch.turn_off
        metadata: {}
        data: {}
        entity_id: !input doseSwitch
      - service: notify.persistent_notification
        data:
          message: '{{ notify_message_fail_max }}'
          title: '{{ notify_title_fail_max }}'
    default:
      - choose: []
        default: !input additional_actions
      - service: switch.turn_on
        data: {}
        entity_id: !input doseSwitch
      - delay: !input doser_time
      - service: switch.turn_off
        data: {}
        entity_id: !input doseSwitch
      - if:
        - condition: template
          value_template: '{{ notify }}'
        then:
        - service: notify.persistent_notification
          data:
            message: '{{ notify_message }}'
            title: '{{ notify_title }}'
  else:
  - if:
    - condition: template
      value_template: '{{ notify }}'
    then:
    - service: notify.persistent_notification
      data:
        message: '{{ notify_message_fail }}'
        title: '{{ notify_title_fail }}'
mode: restart
