blueprint:
  name: Aquarium - Toggle Switches Based on Temperature
  description: This automation blueprint will turn switches on or off when the selected
    temperature sensor is above or below a certain value. (v2.1.1) [Automation]
  domain: automation
  source_url: https://github.com/TheRealFalseReality/aquapi/blob/main/blueprints/automation/TheRealFalseReality/temperature_switch_control.yaml
  input:
    condition:
      name: Add Condition(s)
      description: Add conditions if needed
      default: []
      selector:
        condition: {}
    sensorTemperature:
      name: Temperature Sensor
      description: The sensor that detects temperature.
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    coolTemperature:
      name: Cool Temperature
      description: Toggle devices when the **Temperature Sensor** value crosses below this value.
      default: 74.0
      selector:
        number:
          min: 60.0
          max: 80.0
          unit_of_measurement: °F
          mode: slider
          step: 1.0
    middleTemperature:
      name: Middle Temperature
      description: Toggle devices when the **Temperature Sensor** value crosses this value.
      default: 78.0
      selector:
        number:
          min: 60.0
          max: 90.0
          unit_of_measurement: °F
          mode: slider
          step: 1.0
    warmTemperature:
      name: Warm Temperature
      description: Toggle devices when the **Temperature Sensor** value crosses above this value.
      default: 84.0
      selector:
        number:
          min: 70.0
          max: 90.0
          unit_of_measurement: °F
          mode: slider
          step: 1.0
    actionCool:
      name: Action Cool
      description: Action(s) to run when the **Temperature Sensor** value crosses below the **Cool Temperature** value.
      default: []
      selector:
        action: {}
    actionBetween:
      name: Action Between
      description: Action(s) to run when the **Temperature Sensor** value crosses above the **Cool Temperature** value or below the **Warm Temperature** value.
      default: []
      selector:
        action: {}
    actionMiddleBelow:
      name: Action Middle Below
      description: Action(s) to run when the **Temperature Sensor** value crosses below the **Middle Temperature** value.
      default: []
      selector:
        action: {}
    actionMiddleAbove:
      name: Action Middle Above
      description: Action(s) to run when the **Temperature Sensor** value crosses above the **Middle Temperature** value.
      default: []
      selector:
        action: {}
    actionWarm:
      name: Action Warm
      description: Action(s) to run when the **Temperature Sensor** value crosses above the **Warm Temperature** value.
      default: []
      selector:
        action: {}
    additional_actions:
      name: Additional Actions
      description: Add additional actions to the script. Will execute before everything
        else.
      default: []
      selector:
        action: {}
variables:
  condition: !input condition
  sensorTemperature: !input sensorTemperature
  coolTemperature: !input coolTemperature
  warmTemperature: !input warmTemperature
  actionCool: !input actionCool
  actionWarm: !input actionWarm
  actionBetween: !input actionBetween
  actionMiddleAbove: !input actionMiddleAbove
  actionMiddleBelow: !input actionMiddleBelow
  middleTemperatureRaw: "{{ ((coolTemperature | float) + (warmTemperature | float)) / 2.0 }}"
  middleTemperature: !input middleTemperature
  additional_actions: !input additional_actions
trigger:
- platform: numeric_state
  entity_id: !input sensorTemperature
  above: !input warmTemperature
  id: above
- platform: numeric_state
  entity_id: !input sensorTemperature
  below: !input coolTemperature
  id: below
- platform: numeric_state
  entity_id: !input sensorTemperature
  below: !input warmTemperature
  above: !input coolTemperature
  id: between
- platform: numeric_state
  entity_id: !input sensorTemperature
  below: !input middleTemperature
  id: middlle_below
- platform: numeric_state
  entity_id: !input sensorTemperature
  above: !input middleTemperature
  id: middlle_above
condition: []
action:
- if:
  - condition: !input condition
  then:
  - choose: []
    default: !input additional_actions
  - choose:
    - conditions:
      - condition: trigger
        id:
          - above
      sequence:
      - choose: []
        default: !input actionWarm
    - conditions:
      - condition: trigger
        id:
          - below
      sequence:
      - choose: []
        default: !input actionCool
    - conditions:
      - condition: trigger
        id:
          - middlle_below
      sequence:
      - choose: []
        default: !input actionMiddleBelow
    - conditions:
      - condition: trigger
        id:
          - middlle_above
      sequence:
      - choose: []
        default: !input actionMiddleAbove
    default:
      - choose: []
        default: !input actionBetween
mode: restart
