blueprint:
  name: 'Aquarium - AquaPi: Continuous Read'
  description: Read AquaPi probe every second for 60 seconds. [More Info]  (v1.1)
    [Script]
  domain: script
  source_url: https://gist.github.com/TheRealFalseReality/31de3a3654209bd4a97317762858c271
  input:
    read_button:
      name: Read Button
      description: "AquaPi button to use.\n\nExamples:\n **AquaPi DEVICENAME EC -
        Read**\n **AquaPi DEVICENAME pH - Read**\n"
      selector:
        entity:
          filter:
          - domain:
            - button
            integration: esphome
          multiple: false
variables:
  read_button: !input read_button
sequence:
- repeat:
    sequence:
    - service: button.press
      metadata: {}
      data: {}
      target:
        entity_id: !input read_button
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    count: 60
mode: restart
