blueprint:
  name: 'Aquarium - AquaPi: Continuous Read'
  description: Read AquaPi probe every second for 60 seconds. [More Info]  (v1.1)
    [Script]
  domain: script
  source_url: https://github.com/TheRealFalseReality/aquapi/blob/main/blueprints/script/TheRealFalseReality/aquapi_ezo_read.yaml
  input:
    read_button:
      name: Read Button
      description: "AquaPi button to use.\n\nExamples:\n **AquaPi DEVICENAME EC -
        Read**\n **AquaPi DEVICENAME pH - Read**\n"
      selector:
        entity:
          filter:
          - domain:
            - button
            integration: esphome
          multiple: false
    time_count:
      name: Read Time
      description: Time, in seconds to read the probe for, max of 300s (5min). (default = 60 seconds)
      default: 60
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
variables:
  read_button: !input read_button
  time_count: !input time_count
sequence:
- repeat:
    sequence:
    - service: button.press
      metadata: {}
      data: {}
      target:
        entity_id: !input read_button
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    count: '{{ time_count }}'
mode: restart
