blueprint:
  name: 'Aquarium - AquaPi: Calibrate Conductivity EZO Probe'
  description: Calibrate Conductivity(EC) probe for the AquaPi, an Atlas Scientific
    EZO board and probe. (v1.1.2) [Script]
  domain: script
  source_url: https://github.com/TheRealFalseReality/aquapi/blob/main/blueprints/script/TheRealFalseReality/ec_calibrate_aquapi.yaml
  input:
    ec_sensor:
      name: Conductivity Sensor
      description: 'Conductivity Sensor to Calibrate

        `DEVICENAME Conductivity`'
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: esphome
            device_class:
            - volatile_organic_compounds_parts
          multiple: false
    ec_selector:
      name: Conductivity Selector
      description: 'Conductivity Selector Entity from the AquaPi to Calibrate

        `DEVICENAME EC - Command Select`'
      selector:
        entity:
          filter:
          - domain:
            - select
            integration: esphome
          multiple: false
    ec_command:
      name: EC Command
      description: 'EC Command Entity from the AquaPi to Calibrate

        `DEVICENAME EC - Command Send Selected`'
      selector:
        entity:
          filter:
          - domain:
            - button
            integration: esphome
          multiple: false
variables:
  ec_sensor: !input ec_sensor
  ec_selector: !input ec_selector
  ec_command: !input ec_command
sequence:
- choose:
  - conditions:
    - condition: numeric_state
      entity_id: !input ec_sensor
      below: 5
    sequence:
    - service: select.select_option
      metadata: {}
      data:
        option: Calibrate @ DRY (WILL RESET CALIBRATION)
      target:
        entity_id: !input ec_selector
    - delay:
        milliseconds: 500
    - service: button.press
      entity_id: !input ec_command
    - service: notify.persistent_notification
      data:
        message: EC - Conductivity Calibrated for DRY/AIR - 0 mS/cm. Now continue to
          LOW - 12.88 mS/cm.
        title: 'EC Calibration: Air'
  - conditions:
    - condition: numeric_state
      entity_id: !input ec_sensor
      above: 10
      below: 15
    sequence:
    - service: select.select_option
      metadata: {}
      data:
        option: Calibrate @ LOW = 12880 (WILL RESET CALIBRATION)
      target:
        entity_id: !input ec_selector
    - delay:
        milliseconds: 500
    - service: button.press
      entity_id: !input ec_command
    - service: notify.persistent_notification
      data:
        message: EC - Conductivity Calibrated for LOW - 12.88 mS/cm. Now continue
          to HIGH - 80 mS/cm.
        title: 'EC Calibration: Low'
  - conditions:
    - condition: numeric_state
      entity_id: !input ec_sensor
      above: 78
      below: 82
    sequence:
    - service: select.select_option
      metadata: {}
      data:
        option: Calibrate @ HIGH = 80000 (WILL RESET CALIBRATION)
      target:
        entity_id: !input ec_selector
    - delay:
        milliseconds: 500
    - service: button.press
      entity_id: !input ec_command
    - service: notify.persistent_notification
      data:
        message: EC - Conductivity Calibrated for HIGH - 80 mS/cm. Now check calibration.
        title: 'EC Calibration: High'
  default:
  - service: select.select_option
    metadata: {}
    data:
      option: Check Calibration
    target:
      entity_id: !input ec_selector
  - delay:
      milliseconds: 500
  - service: button.press
    entity_id: !input ec_command
  - service: notify.persistent_notification
    data:
      message: 'EC - Conductivity Calibration is not within range of AIR: 0 mS/cm,
        LOW: 12.88 mS/cm or HIGH: 80 mS/cm.  (±2 mS/CM)

        Start with in-air, no solution, then Low, and finish with High.'
      title: 'EC Calibration: Not in Range'
mode: restart
