blueprint:
  name: 'Aquarium - AquaPi: Calibrate ORP EZO Probe'
  description: Calibrate ORP probe for the AquaPi, an Atlas Scientific
    EZO board and probe. (v1.1) [Script]
  domain: script
  source_url: https://gist.github.com/TheRealFalseReality/f619b484d63a479004c1d6613b90df1a
  input:
    orp_sensor:
      name: ORP Sensor
      description: 'ORP Sensor to Calibrate

        `DEVICENAME ORP`'
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: esphome
            device_class:
            - voltage
          multiple: false
    orp_selector:
      name: ORP Selector
      description: 'ORP Selector Entity from the AquaPi to Calibrate

        `DEVICENAME ORP - Command Select`'
      selector:
        entity:
          filter:
          - domain:
            - select
            integration: esphome
          multiple: false
    orp_command:
      name: ORP Command
      description: 'ORP Command Entity from the AquaPi to Calibrate

        `DEVICENAME ORP - Command Send Selected`'
      selector:
        entity:
          filter:
          - domain:
            - button
            integration: esphome
          multiple: false
variables:
  orp_sensor: !input orp_sensor
  orp_selector: !input orp_selector
  orp_command: !input orp_command
sequence:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: !input orp_sensor
        above: 220
        below: 230
      sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: Calibrate @ 225 mV (WILL RESET CALIBRATION)
        target:
          entity_id: !input orp_selector
      - service: notify.persistent_notification
        data:
          message: ORP - ORP Calibrated for 225 mV 
          title: 'ORP Calibration: 225 mV'
    default:
    - service: select.select_option
      metadata: {}
      data:
        option: Check Calibration
      target:
        entity_id: !input orp_selector
    - service: notify.persistent_notification
      data:
        message: 'ORP - ORP Calibration is not within range of 225 +/- 5 mV'
        title: 'ORP Calibration: Not in Range'
mode: restart
