blueprint:
  name: 'Aquarium - AquaPi: Calibrate ORP EZO Probe @ 225 mV'
  description: Calibrate ORP probe for the AquaPi, an Atlas Scientific EZO board and
    probe. (v1.2.1) [Script]
  domain: script
  source_url: https://github.com/TheRealFalseReality/aquapi/blob/main/blueprints/script/TheRealFalseReality/orp_calibrate_aquapi.yaml
  input:
    orp_sensor:
      name: ORP Sensor
      description: 'ORP Sensor to Calibrate

        `DEVICENAME ORP`'
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: esphome
            device_class:
            - voltage
          multiple: false
    orp_selector:
      name: ORP Selector
      description: 'ORP Selector Entity from the AquaPi to Calibrate

        `DEVICENAME ORP - Command Select`'
      selector:
        entity:
          filter:
          - domain:
            - select
            integration: esphome
          multiple: false
    orp_command:
      name: ORP Command
      description: 'ORP Command Entity from the AquaPi to Calibrate

        `DEVICENAME ORP - Command Send Selected`'
      selector:
        entity:
          filter:
          - domain:
            - button
            integration: esphome
          multiple: false
variables:
  orp_sensor: !input orp_sensor
  orp_selector: !input orp_selector
  orp_command: !input orp_command
sequence:
- choose:
  - conditions:
    - condition: numeric_state
      entity_id: !input orp_sensor
      above: 210
      below: 230
    sequence:
    - service: select.select_option
      metadata: {}
      data:
        option: Calibrate @ 225 mV (WILL RESET CALIBRATION)
      target:
        entity_id: !input orp_selector
    - delay: 
        milliseconds: 500
    - service: button.press
      entity_id: !input orp_command
    - service: notify.persistent_notification
      data:
        message: ORP - ORP Calibrated for 225 mV
        title: 'ORP Calibration: 225 mV'
  default:
  - service: select.select_option
    metadata: {}
    data:
      option: Check Calibration
    target:
      entity_id: !input orp_selector
  - service: notify.persistent_notification
    data:
      message: ORP - ORP Calibration is not within range of 225 mV (210 - 230 mV)
      title: 'ORP Calibration: Not in Range'
mode: restart
