blueprint:
  name: Aquarium - Feeding
  description: Turn off switches to feed your fish for a certain amount of time. [More
    Info](https://community.home-assistant.io/t/aquarium-turn-off-switches-to-feed-your-fish-for-a-certain-amount-of-time-then-turn-back-on-script/600544/1)
    (1.1) [Script]
  domain: script
  source_url: https://gist.github.com/TheRealFalseReality/06d34488d84e81916768129b0398de25
  input:
    condition:
      name: Add Condition(s)
      description: Add conditions if needed
      default: []
      selector:
        condition: {}
    switch:
      name: Equipment Switch
      description: Switch(es) to turn off equipment.
      selector:
        target:
          entity:
          - domain:
            - switch
    feed_time:
      description: 'Time to turn off equipment (default: 10min).'
      name: Feed Time
      default:
        minutes: 10
      selector:
        duration: {}
    additional_actions:
      name: Additional Actions
      description: Add additional actions to the script. Will execute before everything
        else.
      default: []
      selector:
        action: {}
variables:
  condition: !input condition
  switch: !input switch
  feed_time: !input feed_time
  additional_actions: !input additional_actions
sequence:
- if:
  - condition: !input condition
  then:
  - choose: []
    default: !input additional_actions
  - service: switch.turn_off
    data: {}
    target: !input switch
  - delay: !input feed_time
  - service: switch.turn_on
    data: {}
    target: !input switch
mode: restart
