substitutions:
  # names
  name: "aquapi"
  friendly_name: "AquaPi"

  # App Version - Updated: 8/2023
  appVersion: "0.1c"

  # pins
  sdaPin: "21"
  sclPin: "22"
  
  # EZO Circuit Addresses
  # RTD circuit, who's address is 102
  addRTD: "102"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  project:
    name: TheRealFalseReality.aquapi
    version: "${appVersion}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: verbose

# Enable Home Assistant API
api:

ota:

wifi:
  ap:

captive_portal:

web_server:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  
improv_serial:

# i2c Pins
i2c:
  sda: ${sdaPin}
  scl: ${sclPin}
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    # name: "Internal LED"
    pin: GPIO2
    id: internal_led
    # entity_category: "Config"

sensor:
  # EZO Circuit - EC
  # Conductivity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Conductivity"
    id: rtd_ezo
    address: 102
    unit_of_measurement: ""
    accuracy_decimals: 2
    update_interval: 1s
    state_class: "measurement"

button:
  # Calibrate the temp probe to 100C or Boiling
  - platform: template
    name: "RTD - Calibration - 100C (Boiling)"
    id: rtd_cal_100
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).send_custom("cal,100");

  # Perform Calibration CLEAR
  - platform: template
    name: "RTD - Calibration Clear"
    id: rtd_cal_clear
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).clear_calibration();

  # Perform Calibration Check
  - platform: template
    name: "RTD - Calibration - check"
    id: rtd_cal_check
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).get_calibration();

  # Perform Status Check
  - platform: template
    name: "RTD - Staus Check"
    id: rtd_status
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).send_custom("Status");

  # Get Device Firmware Version
  - platform: template
    name: "RTD - Get Information"
    id: rtd_info
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).get_device_information();

  # Manual Read
  - platform: template
    name: "RTD - Manual Read"
    id: rtd_read
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).get_state();