# Enable logging
substitutions:
  # names
  name: "aquapi"
  friendly_name: "AquaPi"

  # App Version - Updated: 8/2023
  appVersion: "0.1c"

  # pins
  sdaPin: "21"
  sclPin: "22"
  
  # EZO Circuit Addresses
  # DO circuit, who's address is 97
  addDO: "97"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  project:
    name: TheRealFalseReality.aquapi
    version: "${appVersion}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: verbose

# Enable Home Assistant API
api:

ota:

# dashboard_import:
#   package_import_url: github://TheRealFalseReality/aquapi/aquapi_config.yaml@main
#   import_full_config: true

wifi:
  ap:

captive_portal:

web_server:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  
improv_serial:

# i2c Pins
i2c:
  sda: ${sdaPin}
  scl: ${sclPin}
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    # name: "Internal LED"
    pin: GPIO2
    id: internal_led
    # entity_category: "Config"

sensor:
  # EZO Circuit - EC
  # Conductivity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Conductivity"
    id: do_ezo
    address: 97
    unit_of_measurement: ""
    accuracy_decimals: 2
    update_interval: 1s
    state_class: "measurement"

button:
  # Calibrate the DO probe to Air
  - platform: template
    name: "DO - Calibration - Air"
    id: do_cal_air
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).send_custom("cal");

  # Calibrate the DO probe to 0
  - platform: template
    name: "DO - Calibration - 0"
    id: do_cal_0
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).send_custom("cal,0");

  # Perform Calibration CLEAR
  - platform: template
    name: "DO - Calibration Clear"
    id: do_cal_clear
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).clear_calibration();

  # Perform Calibration Check
  - platform: template
    name: "DO - Calibration - check"
    id: do_cal_check
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).get_calibration();

  # Perform Status Check
  - platform: template
    name: "DO - Staus Check"
    id: do_status
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).send_custom("Status");

  # Get Device Firmware Version
  - platform: template
    name: "DO - Get Information"
    id: do_info
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).get_device_information();

  # Manual Read
  - platform: template
    name: "DO - Manual Read"
    id: do_read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).get_state();