blueprint:
  name: Aquarium - Dosing Time
  description: Turn on a switch to activate doser equipment for a certain amount of
    time. 
    [More Info](https://community.home-assistant.io/t/aquarium-turn-on-a-switch-to-activate-doser-equipment-for-a-certain-amount-of-volume-or-time/600546)
    (v1.3) [Script]
  domain: script
  source_url: https://gist.github.com/TheRealFalseReality/9fd8f929b5f6cc32f6e8a67cd8104941
  input:
    condition:
      name: Add Condition(s)
      description: Add conditions if needed
      default: []
      selector:
        condition: {}
    doseName:
      name: Dose Name*
      description: Name of what you are dosing (ex. Marine Trace).
      selector:
        text: {}
    switch:
      name: Doser Switch*
      description: Switch that activates the Doser Equipment.
      selector:
        target:
          entity:
          - domain:
            - switch
    doser_time:
      description: Dosing Time.
      name: Dose Time
      default:
        minutes: 10
      selector:
        duration: {}
    additional_actions:
      name: Additional Actions
      description: "Add additional actions to the script. Will execute before everything
        else.\nVariables: doseName, condition, switch, doser_time,notify_title, notify_message,
        notify_title_fail, notify_message_fail.\n- Example: To send to Mobile Device
        using the official Home Assistant App:\n\n  Notifications -> Send a notification
        via mobile.YOUR_DEVICE_NAME\n  ```\n  service: notify.YOUR_DEVICE_NAME\n  metadata:
        {}\n  data:\n    message: \"{{ notify_message }}\"\n    title: \"{{ notify_title
        }}\"\n  ```\n\n  i.e.: copy {{ notify_message }} into `message`. This will
        switch to \"yaml\" mode. Above is a completed example.\n"
      default: []
      selector:
        action: {}
variables:
  condition: !input condition
  switch: !input switch
  doseName: !input doseName
  doser_time: !input doser_time
  notify_title: '{{ doseName }}'
  notify_message: 'Dosing {{ doseName }}. Duration: {{ doser_time }}.'
  notify_title_fail: '{{ doseName }} Failed'
  notify_message_fail: "Failed to dose {{ doseName }} due to conditions not passing.\n
    Conditions: {{ condition }}"
  additional_actions: !input additional_actions
sequence:
- if:
  - condition: !input condition
  then:
  - choose: []
    default: !input additional_actions
  - service: notify.persistent_notification
    data:
      message: '{{ notify_message }}'
      title: '{{ notify_title }}'
  - service: switch.turn_on
    data: {}
    target: !input switch
  - delay: !input doser_time
  - service: switch.turn_off
    data: {}
    target: !input switch
  else:
  - service: notify.persistent_notification
    data:
      message: '{{ notify_message_fail }}'
      title: '{{ notify_title_fail }}'
mode: restart
