substitutions:
  # names
  name: "aquapi"
  friendly_name: "AquaPi"
  comment: "AquaPi ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi"
  sorting_group_name: "AquaPi "

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_config.yaml@main
  import_full_config: false
      
text_sensor: 
  # AquaPi Version
  - platform: template
    name: "AquaPi Version"
    id: aquapi_version
    icon: mdi:update
    update_interval: '365days'
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    update_interval: '365days'
    lambda: |-
      return {"github.com/TheRealFalseReality/aquapi"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic
