---
substitutions:
  # names
  name: "aquapi"
  friendly_name: "AquaPi"
  comment: "AquaPi ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi"
  sorting_group_name: "AquaPi "
  import: "false"

packages:
  aquapi_app_version: !include aquapi_app_version.yaml

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_config.yaml@main
  import_full_config: "${import}"


  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    lambda: |-
      return {"github.com/TheRealFalseReality/aquapi"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic
