---
substitutions:
  # App Version
  app_version: "26.6.5"
  # github URL
  github_url: "https://github.com/TheRealFalseReality/aquapi"

  # names
  name: "aquapi"
  friendly_name: "AquaPi"
  comment: "AquaPi ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi"
  sorting_group_name: "AquaPi"

  # Hardware Variant
  hardware_variant: "AquaPi Hardware Variants"

text_sensor:
  # AquaPi Version
  - id: !extend app_version
    name: "AquaPi Version"

  # Hardware Variant
  - platform: template
    name: "Hardware Variant"
    id: hardware_variant_sensor
    icon: mdi:developer-board
    lambda: |-
      return {"${hardware_variant}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic