# Board rev 1.2
substitutions:
  binary_pin_2: "34" # yellow 
  binary_pin_3: "35" # blue

binary_sensor:
  - platform: gpio
    id: binary_pin_2
    name: Binary Sensor 2
    pin: 
      number: ${binary_pin_2}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms
    web_server:
      sorting_group_id: sorting_group_misc
  - platform: gpio
    id: binary_pin_3
    name: Binary Sensor 3
    pin: 
      number: ${binary_pin_3}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms
    web_server:
      sorting_group_id: sorting_group_misc
