# Board rev 1.2
substitutions:
  binary_input_1: "34" # yellow 
  binary_input_2: "35" # blue

binary_sensor:
  - platform: gpio
    id: binary_input_1
    name: Binary Input Sensor 1
    pin: 
      number: ${binarypin1}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms
    web_server:
      sorting_group_id: sorting_group_misc
  - platform: gpio
    id: binary_input_2
    name: Binary Input Sensor 2
    pin: 
      number: ${binarypin2}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms
    web_server:
      sorting_group_id: sorting_group_misc
