substitutions:
  binary_1: "13" # yellow
  binary_2: "27" # blue

binary_sensor:
  - platform: gpio
    id: binary_1
    pin: 
      number: ${binary_1}
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Binary 1"
    filters:
      - delayed_on_off: 30ms

  - platform: gpio
    id: binary_2
    pin: 
      number: ${binary_2}
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Binary 2"
    filters:
      - delayed_on_off: 30ms
