# Board rev 1.2
substitutions:
  binarypin1: "34" # yellow 
  binarypin2: "35" # blue

binary_sensor:
  - platform: gpio
    id: binary_pin_1
    name: Leak Sensor
    pin: 
      number: ${binarypin1}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms

  - platform: gpio
    id: binary_pin_2
    name: Binary Sensor 2
    pin: 
      number: ${binarypin2}
      mode:
        input: true
    filters:
      - delayed_on_off: 30ms