# TODO
substitutions:  
  dac_1: "26" # yellow
  dac_2: "25" # blue
  
binary_sensor:
  # DAC Pin 1
  - platform: gpio
    id: aux_1
    disabled_by_default: true
    pin: 
      number: ${dac_1}
      inverted: true
      mode:
        input: true
        pullup: true
    name: DAC 1
    filters:
      - delayed_on_off: 30ms

  # DAC Pin 1
  - platform: gpio
    id: aux_1
    disabled_by_default: true
    pin: 
      number: ${dac_2}
      inverted: true
      mode:
        input: true
        pullup: true
    name: DAC 1
    filters:
      - delayed_on_off: 30ms
