substitutions:
  # Import Config
  import_config: "false"

  # I2C pins
  sdaPin: "26"
  sclPin: "27"

esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  comment: "AquaPiCam ESP32 - Aquarium Camera"
  project:
    name: TheRealFalseReality.aquapi
    version: "${app_version}"
  on_boot: 
    then:
      - light.turn_on: camera_led
      - delay: 500ms
      - light.turn_off: camera_led
      - delay: 500ms
      - light.turn_on: camera_led
      - delay: 500ms
      - light.turn_off: camera_led

esp32:
  board: esp32cam
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_camera_config.yaml@main
  import_full_config: ${import_config}

light:
# Internal Red LED
  - platform: status_led
    id: internal_led
    pin: 33
    
  - platform: binary
    output: camera_pin
    name: Camera LED
    id: camera_led

esp32_camera:
  name: AquaPi Camera
  external_clock:
    pin: 
      number: GPIO0
      ignore_strapping_warning: true
    frequency: 20MHz
  i2c_pins:
    sda: ${sdaPin}
    scl: ${sclPin}
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  # resolution: 1024X768
  # resolution: 720x1280
  # resolution: 1080x1920
  # resolution: 2560x1920
  # jpeg_quality: 10
  # vertical_flip: false
  # horizontal_mirror: False

# esp32_camera_web_server:
#   - port: 8080
#     mode: stream
#   - port: 8081
#     mode: snapshot

# LED Control
output:
  - platform: gpio
    pin: 4
    id: camera_pin