substitutions:
  # Logger Level - Can use VERBOSE for more information in Logs
  logger: "DEBUG"

# Enable logging
logger:
  level: "${logger}"

api:

ota:
  - platform: esphome

wifi: 
  ap:

captive_portal:

web_server:
  version: 3
  
improv_serial:

sensor:
  # Internal Temp.
  - platform: internal_temperature
    name: "Internal Temperature"

  # Wifi Signal 
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    disabled_by_default: true
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Wifi %
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  # Uptime sensor
  - platform: uptime
    name: Uptime 

binary_sensor:
  # API Status
  - platform: status
    name: "Status"

text_sensor: 
  # Hostname
  - platform: template
    name: "Hostname"
    id: hostname
    icon: mdi:cellphone-arrow-down
    lambda: |-
      return {"${name}"};
    entity_category: "diagnostic"

text_sensor:
  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      icon: mdi:wifi-arrow-left-right
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address

button:
  # Soft Restart
  - platform: restart
    id: restart_button
    name: "Restart"

  # Factory Reset
  - platform: factory_reset
    name: Factory Reset (USE WITH CAUTION)
    disabled_by_default: true

  # Safe Mode Restart
  - platform: safe_mode
    name: "Restart in Safe Mode"
    id: restart_safe

  # Shutdown
  - platform: shutdown
    name: "Shutdown"
    disabled_by_default: true
    id: shutdown_button