---
substitutions:
  dhtPin: "18"  # was 25
  update_dht: "60s"
  dht_type: "DHT11"

sensor:
  # DHT
  - platform: dht
    pin: ${dhtPin}
    model: "${dht_type}"
    id: dht_sensor
    temperature:
      name: "Air Temperature"
      id: air_temperature
      web_server:
        sorting_group_id: sorting_group_misc
    humidity:
      name: "Humidity"
      id: relative_humidity
      web_server:
        sorting_group_id: sorting_group_misc
    update_interval: "${update_dht}"
  - platform: absolute_humidity
    name: Absolute Humidity
    temperature: air_temperature
    humidity: relative_humidity
    web_server:
      sorting_group_id: sorting_group_misc
  - platform: template
    name: Dew Point
    id: dew_point
    icon: mdi:thermometer-water
    state_class: "measurement"
    device_class: "temperature"
    unit_of_measurement: "°C"
    lambda: |-
      return ( id(air_temperature).state - (( 100 - id(relative_humidity).state ) / 5 ) );
    web_server:
      sorting_group_id: sorting_group_misc
