substitutions:
  # PMP circuit
  addPMP_white: "103" # White
  update_pmp_white: "60s"

  sorting_group_pump_white_weight: '80'

web_server:
  sorting_groups:
    - id: sorting_group_pump_white
      name: "Pump - White"
      sorting_weight: ${sorting_group_pump_white_weight}

ezo_pmp:
  - id: ezo_pump_white
    address: ${addPMP_white}
    update_interval: "${update_pmp_white}"

api:
  actions: 
    - action: pump_white_dose_volume
      variables: 
        dose_volume: float
      then: 
        - ezo_pmp.dose_volume:
            id: ezo_pump_white
            volume: !lambda 'return dose_volume;'
    - action: pump_white_dose_volume_time
      variables:
        dose_volume: float
        dose_time: float
      then:
        - ezo_pmp.dose_volume_over_time:
            id: ezo_pump_white
            volume: !lambda |-
              return dose_volume;
            duration: !lambda |-
              return dose_time;
    - action: pump_white_dose_flow_rate_time
      variables:
        dose_rate: float
        dose_time: float
      then:
        - ezo_pmp.dose_with_constant_flow_rate:
            id: ezo_pump_white
            volume_per_minute: !lambda |-
              return dose_rate;
            duration: !lambda |-
              return dose_time;
    - action: pump_white_dose_set_calibration
      variables:
        actual_volume: float
      then:
        - ezo_pmp.set_calibration_volume:
            id: ezo_pump_white
            volume: !lambda |-
              return actual_volume;
    - action: pump_white_change_address
      variables:
        address: int
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: !lambda |-
              return address;

sensor:
  - platform: ezo_pmp
    id: ezo_pump_white
    current_volume_dosed:
      id: current_volume_dosed
      name: Pump White - Current Volume Dosed
      disabled_by_default: true
      icon: mdi:cube-scan
      device_class: 'volume'
      unit_of_measurement: 'mL'
      state_class: total
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    total_volume_dosed:
      id: total_volume_dosed
      name: Pump White - Total Volume Dosed
      icon: mdi:timer-sand-empty
      device_class: 'volume'
      unit_of_measurement: 'mL'
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    absolute_total_volume_dosed:
      id: absolute_total_volume_dosed
      disabled_by_default: true
      name: Pump White - Absolute Total Volume Dosed
      icon: mdi:timer-sand-full
      device_class: 'volume'
      state_class: total
      unit_of_measurement: 'mL'
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    last_volume_requested:
      id: last_volume_requested
      name: Pump White - Last Volume Requested
      icon: mdi:history
      disabled_by_default: true
      device_class: 'volume'
      state_class: total
      unit_of_measurement: 'mL'
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    max_flow_rate:
      id: max_flow_rate
      name: Pump White - Max Volume/Time Flow Rate
      icon: mdi:car-speed-limiter
      disabled_by_default: true
      unit_of_measurement: 'mL/min'
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    pump_voltage:
      id: pump_white_voltage
      name: Pump White - Voltage
      icon: mdi:lightning-bolt-circle
      disabled_by_default: true
      device_class: 'voltage'
      web_server:
        sorting_group_id: sorting_group_pump_white

binary_sensor:
  - platform: ezo_pmp
    id: ezo_pump_white
    pump_state:
      id: pump_white_state
      name: Pump White - State
      disabled_by_default: true
      icon: mdi:pump
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    is_paused:
      id: is_paused
      name: Pump White - Paused Status
      disabled_by_default: true
      icon: mdi:pause
      web_server:
        sorting_group_id: sorting_group_pump_white

text_sensor:
  - platform: ezo_pmp
    id: ezo_pump_white
    dosing_mode:
      id: dosing_mode
      name: Pump White - Dosing Mode 
      disabled_by_default: true
      icon: mdi:auto-mode
      web_server:
        sorting_group_id: sorting_group_pump_white
  - platform: ezo_pmp
    id: ezo_pump_white
    calibration_status:
      id: calibration_status
      name: Pump White - Calibration Status
      disabled_by_default: true
      icon: mdi:tape-measure
      web_server:
        sorting_group_id: sorting_group_pump_white

number:
  - platform: template
    id: volume
    icon: mdi:pump
    name: Pump White - Volume to Dose
    disabled_by_default: true
    device_class: 'volume'
    unit_of_measurement: 'mL'
    optimistic: true
    initial_value: 10 # cannot be less than +/-0.1mL
    min_value: -378541
    max_value: 378541 # 100 gal
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    id: duration
    icon: mdi:timer
    name: Pump White - Time to Dose
    disabled_by_default: true
    device_class: 'duration'
    unit_of_measurement: 'min'
    optimistic: true
    initial_value: 1
    min_value: 1
    max_value: 1440 # 24 hours
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    id: flow_rate
    icon: mdi:waves-arrow-right
    name: Pump White - Volume/Time Flow Rat
    disabled_by_default: true
    unit_of_measurement: 'mL/min'
    optimistic: true
    initial_value: 10
    min_value: .5
    max_value: 105 # may need to lower to 40
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_white

button:
  - platform: template
    name: Pump White - Dose Volume for Time
    disabled_by_default: true
    icon: mdi:clock-time-two-outline
    id: dose_over_time
    on_press:
      - ezo_pmp.dose_volume_over_time:
          id: ezo_pump_white
          volume: !lambda |-
            return id(volume).state;
          duration: !lambda |-
            return id(duration).state;
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Dose Continuously
    disabled_by_default: true
    icon: mdi:infinity
    id: dose_continuously
    on_press:
      - ezo_pmp.dose_continuously:
          id: ezo_pump_white
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Dose Volume
    disabled_by_default: true
    icon: mdi:pump
    id: dose_volume
    on_press:
      - ezo_pmp.dose_volume:
          id: ezo_pump_white
          volume: !lambda |-
            return id(volume).state;
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Dose at Volume/Time Flow Rate for Time
    disabled_by_default: true
    icon: mdi:format-text-wrapping-overflow
    id: dose_flow_rate
    on_press:
      - ezo_pmp.dose_with_constant_flow_rate:
          id: ezo_pump_white
          volume_per_minute: !lambda |-
            return id(flow_rate).state;
          duration: !lambda |-
            return id(duration).state;
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Pause Dosing
    disabled_by_default: true
    icon: mdi:pause
    id: dose_pause
    on_press:
      - ezo_pmp.pause_dosing:
          id: ezo_pump_white
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Stop Dosing
    disabled_by_default: true
    icon: mdi:stop
    id: dose_stop
    on_press:
      - ezo_pmp.stop_dosing:
          id: ezo_pump_white
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Clear Total Volume Dosed
    disabled_by_default: true
    icon: mdi:backspace
    id: dose_clear
    on_press:
      - ezo_pmp.clear_total_volume_dosed:
          id: ezo_pump_white
    web_server:
      sorting_group_id: sorting_group_pump_white

  # Calibrate
  - platform: template
    name: Pump White - Set Calibration Volume
    disabled_by_default: true
    icon: mdi:tape-measure
    id: dose_calibrate_volume
    on_press:
      - ezo_pmp.set_calibration_volume:
          id: ezo_pump_white
          volume: !lambda |-
            return id(volume).state;
    web_server:
      sorting_group_id: sorting_group_pump_white
  - platform: template
    name: Pump White - Clear Calibration Volume
    icon: mdi:cancel
    disabled_by_default: true
    id: dose_calibrate_volume_clear
    on_press:
      - ezo_pmp.clear_calibration:
          id: ezo_pump_white
    web_server:
      sorting_group_id: sorting_group_pump_white