---
substitutions:
  # O2 circuit, who's address is 108
  addO2: "108" # TODO Matched EZO Pump Red
  update_o2: "60s"
  update_button_o2: "60s"

  sorting_group_o2: '34'

web_server:
  sorting_groups:
    - id: sorting_group_o2
      name: "O2 (Gaseous) - EZO"
      sorting_weight: ${sorting_group_o2}

api:
  actions:
    - action: o2_change_address
      variables:
        address: int
      then:
        - lambda: |-
            id(o2_ezo).send_custom("I2C,{{address}}");
    - action: o2_custom_command
      variables:
        command: string
      then:
        - lambda: |-
            id(o2_ezo).send_custom({{command}});

sensor:
  # EZO Circuits (SCL/RX, SDA/TX)
  # EZO Circuit - O2
  # Oxygen (Gaseous)
  - platform: ezo
    # icon: mdi:molecule-co2
    name: "Oxygen (Gaseous)"
    disabled_by_default: true
    id: o2_ezo
    address: ${addO2}
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: "${update_o2}"
    state_class: "measurement"
    on_calibration:
      then:
        - lambda:
            id(result_o2).publish_state(x);
    on_device_information:
      then:
        - lambda:
            id(result_o2).publish_state(x);
    web_server:
      sorting_group_id: sorting_group_o2
      sorting_weight: 10

text_sensor:
  # Selected Command Result - O2
  - platform: template
    name: O2 - Command Result
    id: result_o2
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_o2

button:
  # Read O2 Sensor
  - platform: template
    name: O2 - Read
    id: read_o2
    icon: mdi:read
    entity_category: "Config"
    disabled_by_default: true
    on_press:
      then:
        - lambda: |-
            esphome::i2c::ErrorCode err = id(bus_a)->write(${addO2}, nullptr, 0);
            if (err == esphome::i2c::ERROR_OK) {
              id(o2_ezo).send_custom("R");
            }
            else {
              ESP_LOGW("custom_o2_read", "No Oxygen (Gaseous) sensor detected at address: ${addO2}!");
            }
    web_server:
      sorting_group_id: sorting_group_o2

  # Send Selected EZO Command - O2
  - platform: template
    name: O2 - Command Send Selected
    id: send_selected_o2
    entity_category: "Config"
    disabled_by_default: true
    on_press:
      then:
        - lambda: |-
            if (id(select_command_o2).current_option() == "Read") {
              id(o2_ezo).send_custom("R");
            }
            if (id(select_command_o2).current_option() == "Information") {
              id(o2_ezo).get_device_information();
            }
            if (id(select_command_o2).current_option() == "Status") {
              id(o2_ezo).send_custom("Status");
            }
            if (id(select_command_o2).current_option() == "Check Calibration") {
              id(o2_ezo).get_calibration();
            }
            else {
              id(o2_ezo).send_custom("R");
            }
    web_server:
      sorting_group_id: sorting_group_o2

select:
  - platform: template
    name: O2 - Command Select
    id: select_command_o2
    disabled_by_default: true
    optimistic: true
    entity_category: "Config"
    options:
      - "Read"
      - "Information"
      - "Status"
      - "Check Calibration"
    initial_option: "Check Calibration"
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]
    web_server:
      sorting_group_id: sorting_group_o2
