substitutions:
  # PMP circuit, who's address is 103
  addPMP_default: "103"
  addPMP_alt1: "108"
  addPMP_alt2: "109"
  addPMP_alt3: "110"

button:
  # Send EZO Command - Custom
  - platform: template
    name: EZO - Send Custom Command
    id: send_custom
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(commmand_custom).state;

text:
    platform: template
    name: EZO - Custom Command
    id: commmand_custom
    entity_category: "Config"
    mode: text
    optimistic: true