---
substitutions:
  #  # PMP circuit, who's default address is 103
  addPMP_white: "103"  # White
  addPMP_red: "108"  # Waste/Red
  addPMP_green: "109"  # Clean/Green
  addPMP_orange: "110"  # Orange
  addPMP_blue: "106"  # Blue
  addPMP_yellow: "104"  # Yellow
  addEC: "100"
  addCO2: "105"
  addDO: "97"
  addHUM: "111"
  addO2: "108"
  addPH: "99"
  addRTD: "102"

button:
  # Change I2C Address of EZO-PMP
  - platform: template
    name: "Pump(Blue) ${addPMP_white} -> ${addPMP_blue} - Change I2C Address"
    entity_category: "Config"
    on_press:
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: ${addPMP_blue}
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Pump(Yellow) ${addPMP_white} -> ${addPMP_yellow} - Change I2C Address"
    entity_category: "Config"
    on_press:
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: ${addPMP_yellow}
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Pump(Red) ${addPMP_white} -> ${addPMP_red} - Change I2C Address"
    entity_category: "Config"
    on_press:
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: ${addPMP_red}
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Pump(Green) ${addPMP_white} -> ${addPMP_green} - Change I2C Address"
    entity_category: "Config"
    on_press:
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: ${addPMP_green}
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Pump(Orange) ${addPMP_white} -> ${addPMP_orange} - Change I2C Address"
    entity_category: "Config"
    on_press:
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_white
            address: ${addPMP_orange}
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-EC"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(ec_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-CO2"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(co2_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-DO"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).send_custom("Plock,1");
    web_server:
        sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-HUM"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(hum_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-O2"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(o2_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-PH"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(ph_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-RTD"
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(rtd_ezo).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  # Change I2C Address of EZO-PMP
  - platform: template
    name: "Lock EZO-PUMP White"
    entity_category: "Config"
    on_press:
      then:
          - lambda: |-
              id(ezo_pump_white).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-PUMP Blue"
    entity_category: "Config"
    on_press:
      then:
          - lambda: |-
              id(ezo_pump_blue).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-PUMP Red"
    entity_category: "Config"
    on_press:
      then:
          - lambda: |-
              id(ezo_pump_red).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-PUMP Green"
    entity_category: "Config"
    on_press:
      then:
          - lambda: |-
              id(ezo_pump_green).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config

  - platform: template
    name: "Lock EZO-PUMP Orange"
    entity_category: "Config"
    on_press:
      then:
          - lambda: |-
              id(ezo_pump_orange).send_custom("Plock,1");
    web_server:
      sorting_group_id: sorting_group_config
