substitutions:
  # PMP circuit
  addPMP_orange: "110" # Orange
  update_pmp_orange: "60s"
  sorting_group_pump_orange_weight: '84'

web_server:
  sorting_groups:
    - id: sorting_group_pump_orange
      name: "Pump - Orange"
      sorting_weight: ${sorting_group_pump_orange_weight}

ezo_pmp:
  - id: ezo_pump_orange
    address: ${addPMP_orange}
    update_interval: "${update_pmp_orange}"

api:
  actions:
    - action: pump_orange_dose_volume
      variables:
        dose_volume: float
      then:
        - ezo_pmp.dose_volume:
            id: ezo_pump_orange
            volume: !lambda 'return dose_volume;'
    - action: pump_orange_dose_volume_time
      variables:
        dose_volume: float
        dose_time: float
      then:
        - ezo_pmp.dose_volume_over_time:
            id: ezo_pump_orange
            volume: !lambda |-
              return dose_volume;
            duration: !lambda |-
              return dose_time;
    - action: pump_orange_dose_flow_rate_time
      variables:
        dose_rate: float
        dose_time: float
      then:
        - ezo_pmp.dose_with_constant_flow_rate:
            id: ezo_pump_orange
            volume_per_minute: !lambda |-
              return dose_rate;
            duration: !lambda |-
              return dose_time;
    - action: pump_orange_dose_set_calibration
      variables:
        actual_volume: float
      then:
        - ezo_pmp.set_calibration_volume:
            id: ezo_pump_orange
            volume: !lambda |-
              return actual_volume;
    - action: pump_orange_change_address
      variables:
        address: int
      then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump_orange
            address: !lambda |-
              return address;

sensor:
  - platform: ezo_pmp
    id: ezo_pump_orange
    current_volume_dosed:
      id: current_volume_dosed_orange
      name: Pump Orange - Current Volume Dosed
      icon: mdi:cube-scan
      device_class: 'volume'
      state_class: total
      unit_of_measurement: 'mL'
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    total_volume_dosed:
      id: total_volume_dosed_orange
      name: Pump Orange - Total Volume Dosed
      icon: mdi:timer-sand-empty
      device_class: 'volume'
      unit_of_measurement: 'mL'
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    absolute_total_volume_dosed:
      id: absolute_total_volume_dosed_orange
      name: Pump Orange - Absolute Total Volume Dosed
      icon: mdi:timer-sand-full
      disabled_by_default: true
      device_class: 'volume'
      state_class: total
      unit_of_measurement: 'mL'
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    last_volume_requested:
      id: last_volume_requested_orange
      name: Pump Orange - Last Volume Requested
      icon: mdi:history
      device_class: 'volume'
      disabled_by_default: true
      state_class: total
      unit_of_measurement: 'mL'
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    max_flow_rate:
      id: max_flow_rate_orange
      name: Pump Orange - Max Volume/Time Flow Rate
      icon: mdi:car-speed-limiter
      disabled_by_default: true
      unit_of_measurement: 'mL/min'
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    pump_voltage:
      id: pump_orange_voltage
      name: Pump Orange - Voltage
      disabled_by_default: true
      icon: mdi:lightning-bolt-circle
      device_class: 'voltage'
      web_server:
        sorting_group_id: sorting_group_pump_orange

binary_sensor:
  - platform: ezo_pmp
    id: ezo_pump_orange
    pump_state:
      id: pump_orange_state
      name: Pump Orange - State
      icon: mdi:pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    is_paused:
      id: is_paused_orange
      name: Pump Orange - Paused Status
      icon: mdi:pause
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_pump_orange

text_sensor:
  - platform: ezo_pmp
    id: ezo_pump_orange
    dosing_mode:
      id: dosing_mode_orange
      name: Pump Orange - Dosing Mode
      icon: mdi:auto-mode
      web_server:
        sorting_group_id: sorting_group_pump_orange
  - platform: ezo_pmp
    id: ezo_pump_orange
    calibration_status:
      id: calibration_status_orange
      name: Pump Orange - Calibration Status
      disabled_by_default: true
      icon: mdi:tape-measure
      web_server:
        sorting_group_id: sorting_group_pump_orange

number:
  - platform: template
    id: volume_orange
    icon: mdi:pump_orange
    name: Pump Orange - Volume to Dose
    device_class: 'volume'
    unit_of_measurement: 'mL'
    optimistic: true
    initial_value: 10 # cannot be less than +/-0.1mL
    min_value: -378541
    max_value: 378541 # 100 gal
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    id: duration_orange
    icon: mdi:timer
    name: Pump Orange - Time to Dose
    device_class: 'duration'
    unit_of_measurement: 'min'
    optimistic: true
    initial_value: 1
    min_value: 1
    max_value: 1440 # 24 hours
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    id: flow_rate_orange
    icon: mdi:waves-arrow-right
    name: Pump Orange - Volume/Time Flow Rate
    unit_of_measurement: 'mL/min'
    optimistic: true
    initial_value: 10
    min_value: .5
    max_value: 105 # may need to lower to 40
    mode: box
    step: 0.1
    web_server:
      sorting_group_id: sorting_group_pump_orange

button:
  - platform: template
    name: Pump Orange - Dose Volume for Time
    icon: mdi:clock-time-two-outline
    id: dose_over_time_orange
    on_press:
      - ezo_pmp.dose_volume_over_time:
          id: ezo_pump_orange
          volume: !lambda |-
            return id(volume_orange).state;
          duration: !lambda |-
            return id(duration_orange).state;
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Dose Continuously
    icon: mdi:infinity
    id: dose_continuously_orange
    on_press:
      - ezo_pmp.dose_continuously:
          id: ezo_pump_orange
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Dose Volume
    icon: mdi:pump_orange
    id: dose_volume_orange
    on_press:
      - ezo_pmp.dose_volume:
          id: ezo_pump_orange
          volume: !lambda |-
            return id(volume_orange).state;
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Dose at Volume/Time Flow Rate for Time
    icon: mdi:format-text-wrapping-overflow
    id: dose_flow_rate_orange
    on_press:
      - ezo_pmp.dose_with_constant_flow_rate:
          id: ezo_pump_orange
          volume_per_minute: !lambda |-
            return id(flow_rate_orange).state;
          duration: !lambda |-
            return id(duration_orange).state;
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Pause Dosing
    icon: mdi:pause
    id: dose_pause_orange
    on_press:
      - ezo_pmp.pause_dosing:
          id: ezo_pump_orange
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Stop Dosing
    icon: mdi:stop
    id: dose_stop_orange
    on_press:
      - ezo_pmp.stop_dosing:
          id: ezo_pump_orange
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Clear Total Volume Dosed
    disabled_by_default: true
    icon: mdi:backspace
    id: dose_clear_orange
    on_press:
      - ezo_pmp.clear_total_volume_dosed:
          id: ezo_pump_orange
    web_server:
      sorting_group_id: sorting_group_pump_orange

  # Calibrate
  - platform: template
    name: Pump Orange - Set Calibration Volume
    icon: mdi:tape-measure
    id: dose_calibrate_volume_orange
    on_press:
      - ezo_pmp.set_calibration_volume:
          id: ezo_pump_orange
          volume: !lambda |-
            return id(volume_orange).state;
    web_server:
      sorting_group_id: sorting_group_pump_orange
  - platform: template
    name: Pump Orange - Clear Calibration Volume
    disabled_by_default: true
    icon: mdi:cancel
    id: dose_calibrate_volume_clear_orange
    on_press:
      - ezo_pmp.clear_calibration:
          id: ezo_pump_orange
    web_server:
      sorting_group_id: sorting_group_pump_orange
