---
substitutions:
  # RTD circuit, who's address is 102
  addRTD: "102"
  update_rtd: "60s"
  update_button_rtd: "60s"
  range_cool_rtd: "23.5"
  range_warm_rtd: "28"

  sorting_group_rtd: '36'

web_server:
  sorting_groups:
    - id: sorting_group_rtd
      name: "RTD - EZO"
      sorting_weight: ${sorting_group_rtd}

# esphome:
#     on_boot:
#         priority: 800
#         then:
#           - button.press: send_selected_rtd

api:
  actions:
    - action: temperature_rtd_change_address
      variables:
        address: int
      then:
        - lambda: |-
            id(rtd_ezo).send_custom("I2C,{{address}}");
    - action: temperature_rtd_calibrate
      variables:
        value: float
      then:
        - lambda: |-
            id(rtd_ezo).send_custom(("Cal," + to_string(value)).c_str());
    - action: temperature_rtd_custom_command
      variables:
        command: string
      then:
        - lambda: |-
            id(rtd_ezo).send_custom(command.c_str());

# esphome:
#   on_boot:
#     priority: 800
#     then:
#       - button.press: read_rtd

# interval:
#   # Update RTD via button to enable detection check
#   - interval: "${update_button_rtd}"
#     then:
#       - button.press: read_rtd

sensor:
  # EZO Circuits (yellow - SCL/RX, blue - SDA/TX)
  # EZO Circuit - RTD
  # Temperature
  - platform: ezo
    name: "Temperature EZO"
    id: rtd_ezo
    address: ${addRTD}
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    update_interval: "${update_rtd}"
    state_class: "measurement"
    device_class: "temperature"
    web_server:
      sorting_group_id: sorting_group_rtd
      sorting_weight: 10

binary_sensor:
  - platform: template
    name: Ideal Temperature
    id: ideal_temp_rtd
    icon: mdi:thermometer-check
    lambda: |-
      if (id(temp_range_rtd).state == "OK") {
        return true;
      } else {
        return false;
      }
    web_server:
      sorting_group_id: sorting_group_rtd

text_sensor:
  # Temperature Range 1
  - platform: template
    name: Temperature Range
    id: temp_range_rtd
    icon: mdi:thermometer-alert
    update_interval: "${update_rtd}"
    lambda: |-
      if (id(rtd_ezo).state <= id(range_cool_rtd).state) {
        return {"Cool"};
      } else if (id(rtd_ezo).state >= id(range_warm_rtd).state) {
        return {"Warm"};
      } else if (!isnan(id(rtd_ezo).state)) {
        return {"OK"};
      } else {
        return {"Unknown"};
      }
    web_server:
      sorting_group_id: sorting_group_rtd
      sorting_weight: 12

number:
  # Temperature when Cool
  - platform: template
    name: "Temp. Cool °C"
    id: range_cool_rtd
    icon: mdi:thermometer-low
    optimistic: true
    mode: box
    min_value: 0
    max_value: 40
    step: 0.5
    restore_value: true
    initial_value: ${range_cool_rtd}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_rtd
    web_server:
      sorting_group_id: sorting_group_rtd

  # Temperature when Warm
  - platform: template
    name: "Temp. Warm °C"
    icon: mdi:thermometer-high
    id: range_warm_rtd
    optimistic: true
    mode: box
    min_value: 0
    max_value: 40
    step: 0.5
    restore_value: true
    initial_value: ${range_warm_rtd}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_rtd
    web_server:
      sorting_group_id: sorting_group_rtd