substitutions:
  # DO circuit, who's address is 97
  addDO: "97"
  update_do: "60s"

# esphome:
#     on_boot: 
#         priority: 200
#         then:
#           - button.press: send_selected_ph

sensor:
  # EZO Circuits (yellow - SCL/RX, blue - SDA/TX)
  # EZO Circuit - DO
  # Dissolved Oxygen
  - platform: ezo
    icon: mdi:molecule
    name: "Dissolved Oxygen"
    id: do_ezo
    address: ${addDO}
    unit_of_measurement: "mg/L"
    accuracy_decimals: 2
    update_interval: "${update_do}"
    state_class: "measurement"
    disabled_by_default: true
    # on_custom: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_calibration: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_device_information: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_slope: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_t: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x); 