substitutions:
  # RTD circuit, who's address is 102
  addRTD: "102"
  update_rtd: "60s"

# esphome:
#     on_boot: 
#         priority: 200
#         then:
#           - button.press: send_selected_ph

sensor:
  # EZO Circuits (yellow - SCL/RX, blue - SDA/TX)
  # EZO Circuit - RTD
  # Temperature
  - platform: ezo
    name: "Temperature EZO"
    id: temp_ezo
    address: ${addRTD}
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    update_interval: "${update_rtd}"
    state_class: "measurement"
    device_class: "temperature"
    disabled_by_default: true
    # on_custom: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_calibration: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_device_information: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_slope: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x);
    # on_t: 
    #   then:
    #     - lambda: 
    #         id(result_ph).publish_state(x); 