substitutions:
  # RTD circuit, who's address is 102
  addRTD: "102"
  update_rtd: "60s"

  sorting_group_rtd: '36'

web_server:
  sorting_groups:
    - id: sorting_group_rtd
      name: "RTD - EZO"
      sorting_weight: ${sorting_group_rtd}

# esphome:
#     on_boot:
#         priority: 800
#         then:
#           - button.press: send_selected_rtd

api:
  actions:
    - action: temperature_rtd_change_address
      variables:
        address: int
      then:
        - lambda: |-
            id(temp_ezo).send_custom("I2C,{{address}}");
    - action: temperature_rtd_custom_command
      variables:
        command: string
      then:
        - lambda: |-
            id(temp_ezo).send_custom({{command}});

sensor:
  # EZO Circuits (yellow - SCL/RX, blue - SDA/TX)
  # EZO Circuit - RTD
  # Temperature
  - platform: ezo
    name: "Temperature EZO"
    id: temp_ezo
    address: ${addRTD}
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    update_interval: "${update_rtd}"
    state_class: "measurement"
    device_class: "temperature"
    disabled_by_default: true
    # on_custom:
    #   then:
    #     - lambda:
    #         id(result_ph).publish_state(x);
    # on_calibration:
    #   then:
    #     - lambda:
    #         id(result_ph).publish_state(x);
    # on_device_information:
    #   then:
    #     - lambda:
    #         id(result_ph).publish_state(x);
    # on_slope:
    #   then:
    #     - lambda:
    #         id(result_ph).publish_state(x);
    # on_t:
    #   then:
    #     - lambda:
    #         id(result_ph).publish_state(x);
    web_server:
      sorting_group_id: sorting_group_rtd
      sorting_weight: 10
