substitutions:
  # PMP circuit, who's address is 103
  addPMP: "103"
  update_pmp: "60s"

ezo_pmp:
  id: ezo_pump
  address: ${addPMP}
  update_interval: "${update_pmp}"

sensor:
  - platform: ezo_pmp
    current_volume_dosed:
      id: current_volume_dosed
      name: Pump - Current Volume Dosed
      icon: mdi:pump
  - platform: ezo_pmp
    total_volume_dosed:
      id: total_volume_dosed
      name: Pump - Total Volume Dosed
      icon: mdi:timer-sand-empty
  - platform: ezo_pmp
    absolute_total_volume_dosed:
      id: absolute_total_volume_dosed
      name: Pump - Absolute Total Volume Dosed
      icon: mdi:timer-sand-full
  - platform: ezo_pmp
    last_volume_requested:
      id: last_volume_requested
      name: Pump - Last Volume Requested
      icon: mdi:history
  - platform: ezo_pmp
    max_flow_rate:
      id: max_flow_rate
      name: Pump - Max Flow Rate
      icon: mdi:car-speed-limiter
  - platform: ezo_pmp
    pump_voltage:
      id: pump_voltage
      name: Pump - Voltage
      disabled_by_default: true

binary_sensor:
  - platform: ezo_pmp
    pump_state:
      id: pump_state
      name: Pump - State
  - platform: ezo_pmp
    is_paused:
      id: is_paused
      name: Pump - Paused Status
      disabled_by_default: true

text_sensor:
  - platform: ezo_pmp
    dosing_mode:
      id: dosing_mode
      name: Pump - Dosing Mode 
      icon: mdi:auto-mode
  - platform: ezo_pmp
    calibration_status:
      id: calibration_status
      name: Pump - Calibration Status
      disabled_by_default: true
      icon: mdi:tape-measure

number:
  - platform: template
    id: volume
    icon: mdi:pump
    name: "Pump - Volume to Dose"
    optimistic: true
    min_value: 0
    max_value: 100
    mode: box
    step: 0.01
  - platform: template
    id: duration
    icon: mdi:pump
    name: "Pump - Duration to Dose (minutes)"
    optimistic: true
    min_value: 0
    max_value: 100
    mode: box
    step: 0.5

button:
  - platform: template
    name: "Pump - Dose Over Time"
    icon: mdi:clock-time-two-outline
    on_press:
      - ezo_pmp.dose_volume_over_time:
          id: ezo_pump
          volume: !lambda |-
                  return id(volume).state;
          duration: !lambda |-
                  return id(duration).state;