substitutions:
  # PMP circuit, who's address is 103
  addPMP_default: "103"
  addPMP_alt1: "108"
  addPMP_alt2: "109"
  addPMP_alt3: "110"

button:
  # Change I2C Address of EZO-PMP
  - platform: template
    name: "Pump(Blue) -> ${addPMP_default} - Change I2C Address"
    on_press:
        then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump
            address: ${addPMP_default}

  - platform: template
    name: "Pump(Red) -> ${addPMP_alt1} - Change I2C Address"
    on_press:
        then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump
            address: ${addPMP_alt1}

  - platform: template
    name: "Pump(Green) -> ${addPMP_alt2} - Change I2C Address"
    on_press:
        then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump
            address: ${addPMP_alt2}

  - platform: template
    name: "Pump(Orange) -> ${addPMP_alt3} - Change I2C Address"
    on_press:
        then:
        - ezo_pmp.change_i2c_address:
            id: ezo_pump
            address: ${addPMP_alt3}