substitutions:
  # PMP circuit, who's address is 103
  addPMPWaste: "108" # Red - Waste Water
  addPMPClean: "109" # Green - Clean Water
  update_pmp: "60s"
  
ezo_pmp:
  - id: ezo_pump_waste
    address: ${addPMPWaste}
    update_interval: "${update_pmp}"
  - id: ezo_pump_clean
    address: ${addPMPClean}
    update_interval: "${update_pmp}"

api:
  services: 
    - service: pump_waste_volume
      variables: 
        dose_volume: float
      then: 
        - ezo_pmp.dose_volume:
            id: ezo_pump_waste
            volume: !lambda 'return dose_volume;'
    - service: pump_waste_volume_time
      variables:
        dose_volume: float
        dose_time: float
      then:
        - ezo_pmp.dose_volume_over_time:
            id: ezo_pump_waste
            volume: !lambda |-
              return dose_volume;
            duration: !lambda |-
              return dose_time;
    - service: pump_waste_flow_rate_time
      variables:
        dose_rate: float
        dose_time: float
      then:
        - ezo_pmp.dose_with_constant_flow_rate:
            id: ezo_pump_waste
            volume_per_minute: !lambda |-
              return dose_rate;
            duration: !lambda |-
              return dose_time;
    - service: pump_waste_set_calibration
      variables:
        actual_volume: float
      then:
        - ezo_pmp.set_calibration_volume:
            id: ezo_pump_waste
            volume: !lambda |-
              return actual_volume;
    - service: pump_clean_volume
      variables: 
        dose_volume: float
      then: 
        - ezo_pmp.dose_volume:
            id: ezo_pump_clean
            volume: !lambda 'return dose_volume;'
    - service: pump_clean_volume_time
      variables:
        dose_volume: float
        dose_time: float
      then:
        - ezo_pmp.dose_volume_over_time:
            id: ezo_pump_clean
            volume: !lambda |-
              return dose_volume;
            duration: !lambda |-
              return dose_time;
    - service: pump_clean_flow_rate_time
      variables:
        dose_rate: float
        dose_time: float
      then:
        - ezo_pmp.dose_with_constant_flow_rate:
            id: ezo_pump_clean
            volume_per_minute: !lambda |-
              return dose_rate;
            duration: !lambda |-
              return dose_time;
    - service: pump_clean_set_calibration
      variables:
        actual_volume: float
      then:
        - ezo_pmp.set_calibration_volume:
            id: ezo_pump_clean
            volume: !lambda |-
              return actual_volume;

sensor:
  - platform: ezo_pmp
    id: ezo_pump_waste
    current_volume_dosed:
      id: current_volume_dosed_waste
      name: Pump Waste - Current Volume Dosed
      icon: mdi:cube-scan
  # - platform: ezo_pmp
    # id: ezo_pump_waste
  #   total_volume_dosed:
  #     id: total_volume_dosed_waste
  #     name: Pump Waste - Total Volume Dosed
  #     icon: mdi:timer-sand-empty
  - platform: ezo_pmp
    id: ezo_pump_waste
    absolute_total_volume_dosed:
      id: absolute_total_volume_dosed_waste
      name: Pump Waste - Absolute Total Volume Dosed
      icon: mdi:timer-sand-full
  - platform: ezo_pmp
    id: ezo_pump_waste
    last_volume_requested:
      id: last_volume_requested_waste
      name: Pump Waste - Last Volume Requested
      icon: mdi:history
  - platform: ezo_pmp
    id: ezo_pump_waste
    max_flow_rate:
      id: max_flow_rate_waste
      name: Pump Waste - Max Volume/Time Flow Rate
      icon: mdi:car-speed-limiter
  # - platform: ezo_pmp
  #   id: ezo_pump_waste
  #   pump_voltage:
  #     id: pump_voltage_waste
  #     name: Pump Waste - Voltage
  #     disabled_by_default: true
  - platform: ezo_pmp
    id: ezo_pump_clean
    current_volume_dosed:
      id: current_volume_dosed_clean
      name: Pump Clean - Current Volume Dosed
      icon: mdi:cube-scan
  # - platform: ezo_pmp
    # id: ezo_pump_clean
  #   total_volume_dosed:
  #     id: total_volume_dosed_clean
  #     name: Pump Clean - Total Volume Dosed
  #     icon: mdi:timer-sand-empty
  - platform: ezo_pmp
    id: ezo_pump_clean
    absolute_total_volume_dosed:
      id: absolute_total_volume_dosed_clean
      name: Pump Clean - Absolute Total Volume Dosed
      icon: mdi:timer-sand-full
  - platform: ezo_pmp
    id: ezo_pump_clean
    last_volume_requested:
      id: last_volume_requested_clean
      name: Pump Clean - Last Volume Requested
      icon: mdi:history
  - platform: ezo_pmp
    id: ezo_pump_clean
    max_flow_rate:
      id: max_flow_rate_clean
      name: Pump Clean - Max Volume/Time Flow Rate
      icon: mdi:car-speed-limiter
  # - platform: ezo_pmp
    # id: ezo_pump_clean
  #   pump_voltage:
  #     id: pump_voltage_clean
  #     name: Pump Clean - Voltage
  #     disabled_by_default: true

binary_sensor:
  - platform: ezo_pmp
    id: ezo_pump_waste
    pump_state:
      id: pump_state_waste
      name: Pump Waste - State
  # - platform: ezo_pmp
    # id: ezo_pump_waste
  #   is_paused:
  #     id: is_paused
  #     name: Pump Waste - Paused Status
  #     disabled_by_default: true
  - platform: ezo_pmp
    id: ezo_pump_clean
    pump_state:
      id: pump_state_clean
      name: Pump Clean - State
  # - platform: ezo_pmp
    # id: ezo_pump_clean
  #   is_paused:
  #     id: is_paused
  #     name: Pump Clean - Paused Status
  #     disabled_by_default: true


text_sensor:
  - platform: ezo_pmp
    id: ezo_pump_waste
    dosing_mode:
      id: dosing_mode_waste
      name: Pump Waste - Dosing Mode 
      icon: mdi:auto-mode
  - platform: ezo_pmp
    id: ezo_pump_waste
    calibration_status:
      id: calibration_status_waste
      name: Pump Waste - Calibration Status
      # disabled_by_default: true
      icon: mdi:tape-measure
  - platform: ezo_pmp
    id: ezo_pump_clean
    dosing_mode:
      id: dosing_mode_clean
      name: Pump Clean - Dosing Mode 
      icon: mdi:auto-mode
  - platform: ezo_pmp
    id: ezo_pump_clean
    calibration_status:
      id: calibration_status_clean
      name: Pump Clean - Calibration Status
      # disabled_by_default: true
      icon: mdi:tape-measure

number:
  - platform: template
    id: volume_waste
    icon: mdi:pump
    name: Pump Waste - Volume to Dose (mL)
    optimistic: true
    initial_value: 10 # cannot be less than +/-0.1mL
    min_value: -378541
    max_value: 378541 # 100 gal
    mode: box
    step: 0.1
  - platform: template
    id: duration_waste
    icon: mdi:timer
    name: Pump Waste - Time to Dose (minutes)
    optimistic: true
    initial_value: 1
    min_value: 1
    max_value: 1440 # 24 hours
    mode: box
    step: 0.1
  - platform: template
    id: flow_rate_waste
    icon: mdi:pump
    name: Pump Waste - Volume/Time Flow Rate (mL/min)
    optimistic: true
    initial_value: 10
    min_value: .5
    max_value: 105 # may need to lower to 40
    mode: box
    step: 0.1
  - platform: template
    id: volume_clean
    icon: mdi:pump
    name: Pump Clean - Volume to Dose (mL)
    optimistic: true
    initial_value: 10 # cannot be less than +/-0.1mL
    min_value: -378541
    max_value: 378541 # 100 gal
    mode: box
    step: 0.1
  - platform: template
    id: duration_clean
    icon: mdi:timer
    name: Pump Clean - Time to Dose (minutes)
    optimistic: true
    initial_value: 1
    min_value: 1
    max_value: 1440 # 24 hours
    mode: box
    step: 0.1
  - platform: template
    id: flow_rate_clean
    icon: mdi:pump
    name: Pump Clean - Volume/Time Flow Rate (mL/min)
    optimistic: true
    initial_value: 10
    min_value: .5
    max_value: 105 # may need to lower to 40
    mode: box
    step: 0.1

button:
  # TODO Make UI
  - platform: template
    name: Pump Waste - Dose Volume for Time
    icon: mdi:clock-time-two-outline
    id: dose_over_time_waste
    on_press:
      - ezo_pmp.dose_volume_over_time:
          id: ezo_pump_waste
          volume: !lambda |-
            return id(volume_waste).state;
          duration: !lambda |-
            return id(duration_waste).state;
  - platform: template
    name: Pump Waste - Dose Continuously
    icon: mdi:infinity
    id: dose_continuously_waste
    on_press:
      - ezo_pmp.dose_continuously:
          id: ezo_pump_waste
  - platform: template
    name: Pump Waste - Dose Volume
    icon: mdi:pump
    id: dose_volume_waste
    on_press:
      - ezo_pmp.dose_volume:
          id: ezo_pump_waste
          volume: !lambda |-
            return id(volume_waste).state;
  - platform: template
    name: Pump Waste - Dose at Volume/Time Flow Rate for Time
    icon: mdi:format-text-wrapping-overflow
    id: dose_flow_rate_waste
    on_press:
      - ezo_pmp.dose_with_constant_flow_rate:
          id: ezo_pump_waste
          volume_per_minute: !lambda |-
            return id(flow_rate_waste).state;
          duration: !lambda |-
            return id(duration_waste).state;
  - platform: template
    name: Pump Waste - Pause Dosing
    icon: mdi:pause
    id: dose_pause_waste
    on_press:
      - ezo_pmp.pause_dosing:
          id: ezo_pump_waste
  - platform: template
    name: Pump Waste - Stop Dosing
    icon: mdi:stop
    id: dose_stop_waste
    on_press:
      - ezo_pmp.stop_dosing:
          id: ezo_pump_waste
  - platform: template
    name: Pump Waste - Clear Total Volume Dosed
    icon: mdi:backspace
    id: dose_clear_waste
    on_press:
      - ezo_pmp.clear_total_volume_dosed:
          id: ezo_pump_waste

  # Calibrate
  - platform: template
    name: Pump Waste - Set Calibration Volume
    icon: mdi:tape-measure
    id: dose_calibrate_volume_waste
    on_press:
      - ezo_pmp.set_calibration_volume:
          id: ezo_pump_waste
          volume: !lambda |-
            return id(volume_waste).state;
  - platform: template
    name: Pump Waste - Clear Calibration Volume
    icon: mdi:cancel
    id: dose_calibrate_volume_clear_waste
    on_press:
      - ezo_pmp.clear_calibration:
          id: ezo_pump_waste
          
  - platform: template
    name: Pump Clean - Dose Volume for Time
    icon: mdi:clock-time-two-outline
    id: dose_over_time_clean
    on_press:
      - ezo_pmp.dose_volume_over_time:
          id: ezo_pump_clean
          volume: !lambda |-
            return id(volume_clean).state;
          duration: !lambda |-
            return id(duration_clean).state;
  - platform: template
    name: Pump Clean - Dose Continuously
    icon: mdi:infinity
    id: dose_continuously_clean
    on_press:
      - ezo_pmp.dose_continuously:
          id: ezo_pump_clean
  - platform: template
    name: Pump Clean - Dose Volume
    icon: mdi:pump
    id: dose_volume_clean
    on_press:
      - ezo_pmp.dose_volume:
          id: ezo_pump_clean
          volume: !lambda |-
            return id(volume_clean).state;
  - platform: template
    name: Pump Clean - Dose at Volume/Time Flow Rate for Time
    icon: mdi:format-text-wrapping-overflow
    id: dose_flow_rate_clean
    on_press:
      - ezo_pmp.dose_with_constant_flow_rate:
          id: ezo_pump_clean
          volume_per_minute: !lambda |-
            return id(flow_rate_clean).state;
          duration: !lambda |-
            return id(duration_clean).state;
  - platform: template
    name: Pump Clean - Pause Dosing
    icon: mdi:pause
    id: dose_pause_clean
    on_press:
      - ezo_pmp.pause_dosing:
          id: ezo_pump_clean
  - platform: template
    name: Pump Clean - Stop Dosing
    icon: mdi:stop
    id: dose_stop_clean
    on_press:
      - ezo_pmp.stop_dosing:
          id: ezo_pump_clean
  - platform: template
    name: Pump Clean - Clear Total Volume Dosed
    icon: mdi:backspace
    id: dose_clear_clean
    on_press:
      - ezo_pmp.clear_total_volume_dosed:
          id: ezo_pump_clean

  # Calibrate
  - platform: template
    name: Pump Clean - Set Calibration Volume
    icon: mdi:tape-measure
    id: dose_calibrate_volume_clean
    on_press:
      - ezo_pmp.set_calibration_volume:
          id: ezo_pump_clean
          volume: !lambda |-
            return id(volume_clean).state;
  - platform: template
    name: Pump Clean - Clear Calibration Volume
    icon: mdi:cancel
    id: dose_calibrate_volume_clear_clean
    on_press:
      - ezo_pmp.clear_calibration:
          id: ezo_pump_clean