substitutions:
  irReceiverPin: "35"

remote_receiver:
  id: ir_receiver
  pin:
    number: ${irReceiverPin}
    inverted: true
  # dump:
  #   - raw
  #   - lg
  #   - rc_switch
  # dump: all
  web_server:
    sorting_group_id: sorting_group_misc
