substitutions:  
  # Optical_1
  opticalLowPin: "33" # yellow
  opticalHighPin: "32" # blue

  # Water Level
  update_water: "60s"

esphome:
  on_boot: 
      priority: 200
      then:
        - component.update: water_level

binary_sensor:
  # Optical Sensor - LOW (yellow)
  - platform: gpio
    id: os_low
    # disabled_by_default: true
    pin: 
      number: ${opticalLowPin}
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Optical Sensor: Low"
    filters:
      - delayed_on_off: 30ms
    on_state:
      then:
        component.update: water_level

  # Optical Sensor - HIGH (blue)
  - platform: gpio
    id: os_high
    # disabled_by_default: true
    pin: 
      number: ${opticalHighPin}
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Optical Sensor: High"
    filters:
      - delayed_on_off: 30ms
    on_state:
      then:
        component.update: water_level

text_sensor:
  # Water Level
  - platform: template
    icon: mdi:waves-arrow-up
    name: "Water Level"
    id: water_level
    update_interval: "${update_water}"
    lambda: |-
      if(id(os_high).state == true && id(os_low).state == true) {
        // Water Level is High
        return {"High"};
      }
      if(id(os_high).state == false && id(os_low).state == false) {
        // Water Level is Low
        return {"Low"};
      }
      if(id(os_high).state == false && id(os_low).state == true) {
        // Water Level is Normal
        return {"Normal"};
      } else {
        return {"Uknown or Error"};
      }
