substitutions:
  update_firmware_sensor_interval: 6h

http_request:
  verify_ssl: false

update:
  - platform: http_request
    name: Firmware Update
    update_interval: "${update_firmware_sensor_interval}"
    entity_category: 'diagnostic'
    icon: mdi:update
    id: update_firmware_sensor
    source: https://raw.githubusercontent.com/TheRealFalseReality/aquapi/main/manifest_camera.json

ota:
  - platform: http_request

button:
  - platform: template
    id: update_firmware
    name: Update Firmware (Experimental)
    entity_category: "config"
    # disabled_by_default: true
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/TheRealFalseReality/aquapi/main/bin/ota/aquapicamera.md5
            url: https://raw.githubusercontent.com/TheRealFalseReality/aquapi/main/bin/ota/aquapicamera.ota.bin