substitutions:
  ota_update_interval: 24h

ota:
  - platform: http_request

http_request:
  verify_ssl: false

update:
  - platform: http_request
    name: AquaPi Firmware Update
    id: update_firmware_sensor
    entity_category: 'diagnostic'
    update_interval: ${ota_update_interval}
    icon: mdi:update
    source: https://therealfalsereality.github.io/aquapi/firmware/aquapi.manifest.json
    web_server:
      sorting_group_id: sorting_group_diagnostic

button:
  - platform: template
    id: update_firmware
    name: Update AquaPi Firmware - Stable
    entity_category: "config"
    icon: mdi:update
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_config
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://therealfalsereality.github.io/aquapi/firmware/aquapi-esp32.ota.bin.md5
            url: https://therealfalsereality.github.io/aquapi/firmware/aquapi-esp32.ota.bin