substitutions:
  update_firmware_sensor_interval: 6h

ota:
  - platform: http_request

http_request:
  verify_ssl: false

update:
  - platform: http_request
    name: AquaPi Firmware Update
    update_interval: "${update_firmware_sensor_interval}"
    id: update_firmware_sensor
    entity_category: 'diagnostic'
    icon: mdi:update
    source: https://raw.githubusercontent.com/TheRealFalseReality/aquapi/refs/heads/main/bin/AquaPi.manifest.json

button:
  - platform: template
    id: update_firmware
    name: Update AquaPi Firmware - Releaseed (Experimental - v24.10.14)
    entity_category: "config"
    icon: mdi:update
    disabled_by_default: true
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/TheRealFalseReality/aquapi/refs/heads/main/bin/aquapi-esp32.ota.bin.md5
            url: https://github.com/TheRealFalseReality/aquapi/raw/refs/heads/main/bin/aquapi-esp32.ota.bin