---
substitutions:
  # Device Information
  # App Version
  app_version: "1.0"
  comment: "AquaPi ESP32 - Aquarium Controller & Monitor"
  friendly_name: "AquaPi"
  import: "false"
  # names
  name: "aquapi"
  project_name: "therealfalsereality.aquapi"

  # Logger Settings
  # Logger Level - Can use VERBOSE for more information in Logs
  logger: "DEBUG"

  # Pins
  auxPin1: "26"  # blue
  auxPin2: "27"  # yellow
  binary_pin_1: "13"  # yellow
  binary_pin_2: "18"  # yellow
  binary_pin_3: "19"  # blue
  binary_pin_4: "4"  # yellow
  binary_pin_5: "17"  # blue
  binary_pin_6: "23"  # blue
  dac_1: "26"  # yellow
  dac_2: "25"  # blue
  dallasPin: "16"
  dhtPin: "18"  # was 25
  dht_type: "DHT11"
  irReceiverPin: "35"
  leak_sensor: "27"  # blue -> red (GND - Green -> Black  )
  opticalHighPin: "33"  # blue
  # pins
  opticalLowPin: "32"  # yellow
  temp_address_2: "''"

  # I2C Pins
  sclPin: "22"  # blue/RX PMP -> white
  # I2C pins
  sdaPin: "21"  # yellow/TX PMP -> green

  # EZO Circuit I2C Addresses
  # CO2 circuit, who's address is 105
  addCO2: "105"
  # DO circuit, who's address is 97
  addDO: "97"
  # EC circuit, who's address is 100
  addEC: "100"
  # HUM circuit, who's address is 111
  addHUM: "111"
  # ORP circuit, who's address is 98
  addORP: "98"
  # pH circuit, who's address is 99
  addPH: "99"
  # RTD circuit, who's address is 102
  addRTD: "102"

  # EZO PMP Circuit Addresses
  # PMP circuit, who's address is 103
  addPMP: "103"
  addPMPClean: "109"  # Green - Clean Water
  addPMPWaste: "108"  # Red - Waste Water
  addPMP_2: "110"  # Orange
  addPMP_3: "104"  # Yellow
  addPMP_4: "106"  # Blue
  addPMP_blue: "106"  # Blue
  addPMP_green: "109"  # Clean/Green
  addPMP_orange: "110"  # Orange
  addPMP_red: "108"  # Waste/Red
  #  # PMP circuit, who's default address is 103
  addPMP_white: "103"  # White
  addPMP_yellow: "104"  # Yellow

  # Calibration Variables
  # Calibration Temp. 1
  cal_0: "0.0"
  # Calibration Temp. 2
  cal_0_2: "0.0"
  #  # Calibration Temp. 2
  cal_0_temp_2: "0.0"
  cal_100: "100.0"
  cal_100_2: "100.0"
  cal_100_temp_2: "100.0"
  range_cool: "74"
  range_warm: "82"

  # Sensor Update Intervals
  update_button_co2: "60s"
  update_button_do: "60s"
  update_button_ec: "60s"
  update_button_hum: "60s"
  update_co2: "60s"
  update_dht: "60s"
  update_do: "60s"
  update_ec: "60s"
  update_hum: "60s"
  update_orp: "60s"
  update_ph: "60s"
  # EZO PMP
  update_pmp: "60s"
  update_pmp_blue: "60s"
  update_pmp_green: "60s"
  update_pmp_orange: "60s"
  update_pmp_red: "60s"
  update_pmp_white: "60s"
  update_pmp_yellow: "60s"
  update_rtd: "60s"
  # Temp. Probes
  update_temp: "60s"
  # Water Level
  update_water: "60s"

  # Sorting Groups
  sorting_group_co2: "'34'"
  sorting_group_config_weight: "'99'"
  sorting_group_debug: "'96'"
  sorting_group_diagnostic_weight: "'98'"
  sorting_group_do: "'32'"
  sorting_group_ec: "'31'"
  sorting_group_hum: "'35'"
  sorting_group_misc_weight: "'97'"
  sorting_group_name: "AquaPi"
  sorting_group_orp: "'33'"
  sorting_group_ph: "'30'"
  sorting_group_pump_blue_weight: "'83'"
  sorting_group_pump_green_weight: "'81'"
  sorting_group_pump_orange_weight: "'84'"
  sorting_group_pump_red_weight: "'82'"
  sorting_group_pump_white_weight: "'80'"
  sorting_group_pump_yellow_weight: "'85'"
  sorting_group_rtd: "'36'"
  sorting_group_temperature_weight: "'10'"
  sorting_group_water_level_weight: "'11'"
