---
substitutions:
  dallasPin: "16"
  update_temp: "60s"

  # Calibration variables
  # 0C using Ice Water; 100C using Boiling Water
  # Calibration Temp. 3
  cal_0_temp_3: "0.0"
  cal_100_temp_3: "100.0"
  range_cool_3: "74"
  range_warm_3: "82"

  # Calibration Temp. 4
  cal_0_temp_4: "0.0"
  cal_100_temp_4: "100.0"
  range_cool_4: "74"
  range_warm_4: "82"

  sorting_group_temperature_weight: '10'

web_server:
  sorting_groups:
    - id: sorting_group_temperature
      name: "Temperature"
      sorting_weight: ${sorting_group_temperature_weight}

# 18B20 sensor Pin
one_wire:
  - platform: gpio
    pin: ${dallasPin}

sensor:
  # Temperature 3 Probe 3 - Uses index 0 (first sensor on the bus)
  - platform: dallas_temp
    index: 0
    id: temp_3
    icon: mdi:thermometer-water
    name: "Temperature 3"
    state_class: "measurement"
    device_class: "temperature"
    update_interval: "${update_temp}"
    filters:
      - filter_out: NAN
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 0.0 -> ${cal_0_temp_3}
            - 100.0 -> ${cal_100_temp_3}
    on_value:
      then:
        - component.update: temp_range_3
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 10

  # Convert to Fahrenheit - Temp. 3
  - platform: template
    state_class: "measurement"
    device_class: "temperature"
    id: temp_f_3
    lambda: |-
      return id(temp_3).state * 9 / 5 + 32;
    web_server:
      sorting_group_id: sorting_group_temperature

  # Calibration Temp. at 0C
  - platform: template
    name: Calibration at 0°C - Temp. 3
    id: cal_0_sen_3
    icon: mdi:thermometer-low
    unit_of_measurement: "°C"
    disabled_by_default: true
    state_class: "measurement"
    device_class: "temperature"
    entity_category: "diagnostic"
    lambda: |-
      return {${cal_0_temp_3}};
    web_server:
      sorting_group_id: sorting_group_temperature

  # Calibration Temp. at 100C
  - platform: template
    name: Calibration at 100°C - Temp. 3
    id: cal_100_sen_3
    icon: mdi:thermometer-high
    unit_of_measurement: "°C"
    disabled_by_default: true
    state_class: "measurement"
    device_class: "temperature"
    entity_category: "diagnostic"
    lambda: |-
      return {${cal_100_temp_3}};
    web_server:
      sorting_group_id: sorting_group_temperature

  # Temperature 3 Probe 4 - Uses index 1 (second sensor on the bus)
  - platform: dallas_temp
    index: 1
    id: temp_4
    icon: mdi:thermometer-water
    name: "Temperature 4"
    state_class: "measurement"
    device_class: "temperature"
    update_interval: "${update_temp}"
    filters:
      - filter_out: NAN
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 0.0 -> ${cal_0_temp_4}
            - 100.0 -> ${cal_100_temp_4}
    on_value:
      then:
        - component.update: temp_range_4
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 60

  # Convert to Fahrenheit - Temp. 4
  - platform: template
    state_class: "measurement"
    device_class: "temperature"
    id: temp_f_4
    lambda: |-
      return id(temp_4).state * 9 / 5 + 32;
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69

  # Calibration Temp. 4 at 0C
  - platform: template
    name: Calibration at 0°C - Temp. 4
    id: cal_0_4_sen
    disabled_by_default: true
    icon: mdi:thermometer-low
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
    entity_category: "diagnostic"
    lambda: |-
      return {${cal_0_temp_4}};
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69

  # Calibration Temp. 4 at 100C
  - platform: template
    name: Calibration at 100°C - Temp. 4
    id: cal_100_4_sen
    disabled_by_default: true
    icon: mdi:thermometer-high
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
    entity_category: "diagnostic"
    lambda: |-
      return {${cal_100_temp_4}};
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69

binary_sensor:
  - platform: template
    name: Ideal Temperature 3
    id: ideal_temp
    icon: mdi:thermometer-check
    lambda: |-
      if (id(temp_range_3).state == "OK") {
        return true;
      } else {
        return false;
      }
    web_server:
      sorting_group_id: sorting_group_temperature

  - platform: template
    name: Ideal Temperature 4
    id: ideal_temp_2
    icon: mdi:thermometer-check
    lambda: |-
      if (id(temp_range_4).state == "OK") {
        return true;
      } else {
        return false;
      }
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69

text_sensor:
  # Temperature 3 Range 1
  - platform: template
    name: Temperature 3 Range
    id: temp_range_3
    icon: mdi:thermometer-alert
    update_interval: "${update_temp}"
    lambda: |-
      if(id(temp_f_3).state <= id(range_cool_3).state) {
        return {"Cool"};
      }
      if(id(temp_f_3).state < id(range_warm_3).state && id(temp_f_3).state > id(range_cool_3).state) {
        return {"OK"};
      }
      if(id(temp_f_3).state >= id(range_warm_3).state) {
        return {"Warm"};
      }
      else {
        return {"Unknown"};
      }
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 12

  # Temperature 3 Range 2
  - platform: template
    name: Temperature 4 Range
    id: temp_range_4
    icon: mdi:thermometer-alert
    update_interval: "${update_temp}"
    lambda: |-
      if(id(temp_f_4).state <= id(range_cool_4).state) {
        return {"Cool"};
      }
      if(id(temp_f_4).state < id(range_warm_4).state && id(temp_f_4).state > id(range_cool_4).state) {
        return {"OK"};
      }
      if(id(temp_f_4).state >= id(range_warm_4).state) {
        return {"Warm"};
      }
      else {
        return {"Unknown"};
      }
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 62

number:
  # Temperature 3 1 when Cool
  - platform: template
    name: "Temp. Cool"
    id: range_cool_3
    icon: mdi:thermometer-low
    optimistic: true
    mode: box
    min_value: 0.0
    max_value: 100.0
    step: 0.5
    restore_value: true
    initial_value: ${range_cool_3}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_3
    web_server:
      sorting_group_id: sorting_group_temperature

  # Temperature 3 1 when Warm
  - platform: template
    name: "Temp. Warm"
    icon: mdi:thermometer-high
    id: range_warm_3
    optimistic: true
    mode: box
    min_value: 0.0
    max_value: 100.0
    step: 0.5
    restore_value: true
    initial_value: ${range_warm_3}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_3
    web_server:
      sorting_group_id: sorting_group_temperature

  # Temperature 4 when Cool
  - platform: template
    name: "Temp. 4 Cool"
    id: range_cool_4
    icon: mdi:thermometer-low
    optimistic: true
    mode: box
    min_value: 0.0
    max_value: 100.0
    step: 0.5
    restore_value: true
    initial_value: ${range_cool_4}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_4
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69

  # Temperature 4 when Warm
  - platform: template
    name: "Temp. 4 Warm"
    icon: mdi:thermometer-high
    id: range_warm_4
    optimistic: true
    mode: box
    min_value: 0.0
    max_value: 100.0
    step: 0.5
    restore_value: true
    initial_value: ${range_warm_4}
    entity_category: "Config"
    device_class: "temperature"
    on_value:
      then:
        - component.update: temp_range_4
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 69
