# CHANGEME: Set these variable to your liking
title: AquaPi powered by ESPHome
avatar: assests/AquaPiLogo_small.png
description: Powered by HomeAssistant & ESPHome
show_downloads: false
google_analytics: G-BPGR2QSCVL
remote_theme: reverie
