title: AquaPi powered by ESPHome
logo: assests/AquaPiLogo_small.png
description: Powered by HomeAssistant & ESPHome
show_downloads: false
google_analytics: G-BPGR2QSCVL
# theme: jekyll-theme-minima
remote_theme: jekyll/minima
minima:
  skin: auto
