name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    env:
      ESPHOME_VERSION: 2023.7.1
    strategy:
      matrix:
        file:
          - aquapi_config.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.6.0
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: ${{ matrix.file }}
