name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - aquapi_config.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.1.0
        with:
          yaml_file: ${{ matrix.file }}
          release_url: https://github.com/TheRealFalseReality/aquapi/releases