name: CI

on:
  push:
  workflow_dispatch:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        #### Modify below here to match your project ####
        file:
          - aquapi_config

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
